package com.software.rmh.walkthroughthebible.Models

/**
 * Created by rhoffman on 2/5/17.
 *
 *
 * Storage of all locations in the KJV Bible.
 */

class BibleLocationsKJV {

	private val allBooks = arrayOf(Genesis, 
                                    Exodus, 
                                    Leviticus, 
                                    Numbers, 
                                    Deuteronomy, 
                                    Joshua, 
                                    Judges, 
                                    Ruth, 
                                    First_Samuel, 
                                    Second_Samuel, 
                                    First_Kings, 
                                    Second_Kings, 
                                    First_Chronicles, 
                                    Second_Chronicles, 
                                    Ezra, 
                                    Nehemiah, 
                                    Esther, 
                                    Job, 
                                    Psalms, 
                                    Proverbs, 
                                    Ecclesiasties, 
                                    Song_of_Solomon, 
                                    Isaiah, 
                                    Jeremiah, 
                                    Lamentations, 
                                    Ezekiel, 
                                    Daniel, 
                                    Hosea, 
                                    Joel, 
                                    Amos, 
                                    Obadiah, 
                                    Jonah, 
                                    Micah, 
                                    Nahum, 
                                    Habakkuk, 
                                    Zechariah, 
                                    Haggai, 
                                    Zephaniah, 
                                    Malachi, 
                                    Matthew, 
                                    Mark, 
                                    Luke, 
                                    John, 
                                    Acts, 
                                    Romans, 
                                    First_Corinthians, 
                                    Second_Corinthians, 
                                    Galatians, 
                                    Ephesians, 
                                    Philippians, 
                                    Colossians, 
                                    First_Thessalonians, 
                                    Second_Thessalonians, 
                                    First_Timothy, 
                                    Second_Timothy, 
                                    Titus, 
                                    Philemon, 
                                    Hebrews, 
                                    James, 
                                    First_Peter, 
                                    Second_Peter, 
                                    First_John, 
                                    Second_John, 
                                    Third_John, 
                                    Jude, 
                                    Revelations)

	fun getBookLocations(book: Int): Array<out Array<out String?>> {
		if (book > 65 || book < 0) {
            // There are 66 books, so must be between 0 and 65
			throw IndexOutOfBoundsException()
		}

		return allBooks[book]
	}

	companion object {

		/**
		 * Old Testament books of the Bible. All locations referenced in every
		 * chapter of every book is stored as a String[]
		 */
		private val Genesis = arrayOf(arrayOf<String?>(null),
				arrayOf("Eden", "Pison", "Havilah", "Gihon", "Ethiopia",
						"Assyria", "Hiddekel", "Euphrates"),
				arrayOf("Eden"),
				arrayOf("Eden"),
				arrayOf<String?>(null),
				arrayOf<String?>(null),
				arrayOf<String?>(null),
				arrayOf("Ararat"),
				arrayOf<String?>(null),
				arrayOf("Babel", "Erech", "Accad", "Calneh", "Shinar",
						"Assyria", "Nineveh", "Rehoboth", "Resen", "Calah",
						"Sidon", "Gerar", "Gaza", "Sodom", "Gomorrah", "Admah",
						"Zeboim", "Lasha", "Mesha", "Sephar"),
				arrayOf("Shinar", "Babel", "Ur of the Chaldees",
						"Haran", "Canaan"),
				arrayOf("Haran", "Canaan", "Shechem", "Moreh", "Bethel",
						"Hai", "Egypt"),
				arrayOf("Egypt", "Negeb", "Bethel", "Hai",
						"plain of Jordan", "Zoar", "Sodom", "Gomorrah", "Canaan",
						"Mamre", "Hebron"),
				arrayOf("Shinar", "Ellasar", "Elam", "Sodom",
						"Gomorrah", "Admah", "Zeboiim", "Bela", "Zoar",
						"vale of Siddim", "salt sea", "Ashteroth Karnaim", "Ham",
						"Shaveh Kiriathaim", "Seir", "Elparan", "Enmishpat",
						"Kadesh", "Engedi", "Hazazontamar", "Hazezontamar",
						"Mamre", "Dan", "Hobah", "Damascus", "valley of Shaveh",
						"king's dale", "Salem"),
				arrayOf("Damascus", "Ur of the Chaldees", "Egypt",
						"Euphrates"),
				arrayOf("Canaan", "Shur", "Beerlahairoi", "Kadesh",
						"Bered"),
				arrayOf("Canaan"),
				arrayOf("Mamre", "Sodom", "Gomorrah"),
				arrayOf("Sodom", "Zoar", "Gomorrah"),
				arrayOf("Negeb", "Kadesh", "Shur", "Gerar"),
				arrayOf("Beersheba", "wilderness of Paran", "Egypt"),
				arrayOf("Moriah", "Beersheba"),
				arrayOf("Kirjatharba", "Hebron", "Canaan", "Machpelah",
						"Mamre"),
				arrayOf("Mesopotamia", "Nahor", "Beerlahairoi", "Negeb"),
				arrayOf("Machpelah", "Ephron", "Mamre", "Beerlahairoi",
						"Havilah", "Shur", "Egypt", "Assyria", "Padanaram"),
				arrayOf("Gerar", "Egypt", "valley of Gerar", "Esek",
						"Sitnah", "Rehoboth", "Beersheba"),
				arrayOf("Haran"),
				arrayOf("Padanaram", "Beersheba", "Haran", "Bethel",
						"Luz"),
				arrayOf("Haran"),
				arrayOf<String?>(null),
				arrayOf("Bethel", "Canaan", "Euphrates", "Gilead",
						"Jegarsahadutha", "Galeed", "Mizpah"),
				arrayOf("Mahanaim", "Seir", "Edom", "Jordan",
						"Jabbok", "Penuel"),
				arrayOf("Seir", "Succoth", "Shechem", "Canaan",
						"Padanaram", "EleloheIsrael"),
				arrayOf("Israel", "Shechem"),
				arrayOf("Bethel", "Shechem", "Luz", "Canaan",
						"Elbethel", "Allonbachuth", "Ephrath", "Bethlehem",
						"Edar", "Padanaram", "Mamre", "Kirjatharba", "Hebron"),
				arrayOf("Canaan", "Seir", "Edom", "Dinhabah", "Moab",
						"Avith", "Euphrates"),
				arrayOf("Canaan", "Shechem", "vale of Hebron",
						"Dothan", "Gilead", "Egypt"),
				arrayOf("Chezib", "Timnah"),
				arrayOf("Egypt"),
				arrayOf("Egypt"),
				arrayOf("the river", "Egypt"),
				arrayOf("Egypt", "Canaan"),
				arrayOf("Egypt"),
				arrayOf("Canaan"),
				arrayOf("Egypt", "Goshen", "Canaan"),
				arrayOf("Beersheba", "Egypt", "Canaan", "Padanaram",
						"Goshen"),
				arrayOf("Canaan", "Goshen", "Egypt", "Rameses"),
				arrayOf("Luz", "Canaan", "Egypt", "Padan", "Ephrath",
						"Bethlehem"),
				arrayOf("Sidon", "Ephron", "Machpelah", "Mamre",
						"Canaan"),
				arrayOf("Canaan", "Egypt", "Goshen", "Atad", "Jordan",
						"Abelmizraim", "Machpelah", "Mamre", "Ephron"))

		private val Exodus = arrayOf(arrayOf("Egypt", "Pithom",
				"Raamses", "the river"),
				arrayOf("Midian", "Egypt"),
				arrayOf("Midian", "Horeb", "Egypt"),
				arrayOf("the river", "Egypt", "Midian"),
				arrayOf("Egypt"),
				arrayOf("Canaan", "Egypt"),
				arrayOf("Egypt", "the river"),
				arrayOf("the river", "Egypt", "Goshen"),
				arrayOf("Egypt", "Goshen"),
				arrayOf("Egypt", "Red sea"),
				arrayOf("Egypt"),
				arrayOf("Egypt", "Rameses", "Succoth (Egypt)"),
				arrayOf("Egypt", "Red sea", "Succoth (Egypt)", "Etham"),
				arrayOf("Pihahiroth", "Migdol", "Baalzephon", "Egypt"),
				arrayOf("Red sea", "Palestina", "Edom", "Moab",
						"Canaan", "Shur", "Marah", "Elim"),
				arrayOf("Elim", "wilderness of Sin", "Sinai", "Egypt",
						"Canaan"),
				arrayOf("wilderness of Sin", "Rephidim", "Egypt",
						"the river", "Horeb", "Massah", "Meribah in Sinai"),
				arrayOf("Midian", "Egypt"),
				arrayOf("Egypt", "Sinai", "Rephidim", "mount Sinai"),
				arrayOf("Egypt"),
				arrayOf<String?>(null),
				arrayOf("Egypt"),
				arrayOf("Egypt", "Red sea", "sea of the Philistines",
						"Euphrates"),
				arrayOf("mount Sinai"),
				arrayOf<String?>(null),
				arrayOf<String?>(null),
				arrayOf<String?>(null),
				arrayOf<String?>(null),
				arrayOf("Egypt"),
				arrayOf<String?>(null),
				arrayOf("mount Sinai"),
				arrayOf("Egypt"),
				arrayOf("Egypt", "mount Horeb"),
				arrayOf("mount Sinai", "Egypt"),
				arrayOf<String?>(null),
				arrayOf<String?>(null),
				arrayOf<String?>(null),
				arrayOf<String?>(null),
				arrayOf<String?>(null),
				arrayOf<String?>(null))

		private val Leviticus = arrayOf(arrayOf("Israel"),
				arrayOf<String?>(null),
				arrayOf<String?>(null),
				arrayOf("Israel"),
				arrayOf<String?>(null),
				arrayOf<String?>(null),
				arrayOf("Israel", "mount Sinai", "wilderness of Sinai"),
				arrayOf<String?>(null),
				arrayOf("Israel"),
				arrayOf("Israel"),
				arrayOf("Egypt", "Israel"),
				arrayOf("Israel"),
				arrayOf<String?>(null),
				arrayOf("Canaan"),
				arrayOf("Israel"),
				arrayOf("Israel"),
				arrayOf("Israel"),
				arrayOf("Canaan", "Egypt", "Israel"),
				arrayOf("Egypt", "Israel"),
				arrayOf("Israel"),
				arrayOf("Israel"),
				arrayOf("Egypt", "Israel"),
				arrayOf("Egypt", "Israel"),
				arrayOf("Dan", "Egypt", "Israel"),
				arrayOf("Canaan", "Egypt", "Israel", "mount Sinai"),
				arrayOf("Egypt", "Israel", "mount Sinai"),
				arrayOf("Israel", "mount Sinai"))

		private val Numbers = arrayOf(arrayOf("wilderness of Sinai",
				"Egypt"),
				arrayOf<String?>(null),
				arrayOf("mount Sinai", "wilderness of Sinai", "Egypt"),
				arrayOf<String?>(null),
				arrayOf<String?>(null),
				arrayOf<String?>(null),
				arrayOf<String?>(null),
				arrayOf("Egypt"),
				arrayOf("wilderness of Sinai", "Egypt"),
				arrayOf("wilderness of Sinai", "wilderness of Paran"),
				arrayOf("Taberah", "Egypt", "Kibrothhattaavah",
						"Hazeroth"),
				arrayOf("Hazeroth", "wilderness of Paran"),
				arrayOf("Canaan", "wilderness of Paran",
						"wilderness of Zin", "Rehob", "Hamath", "Negeb", "Hebron",
						"Zoan", "Egypt", "valley of Eshcol", "Kadesh", "Jordan"),
				arrayOf("Egypt", "Red sea", "Hormah"),
				arrayOf("Egypt"),
				arrayOf<String?>(null),
				arrayOf<String?>(null),
				arrayOf<String?>(null),
				arrayOf<String?>(null),
				arrayOf("wilderness of Zin", "Kadesh", "Meribah",
						"Edom", "Egypt", "mount Hor"),
				arrayOf("Arad", "Negeb", "Atharim", "Hormah",
						"mount Hor", "Red sea", "Edom", "Egypt", "Oboth",
						"Ijeabarim", "Moab", "valley of Zared", "Arnon",
						"Red sea", "Beer", "Mattanah", "Bamoth", "Pisgah",
						"Jahaz", "Jabbok", "Heshbon", "Dibon", "Nophah", "Medeba",
						"Jazer", "Bashan", "Edrei"),
				arrayOf("Moab", "Jordan", "Jericho", "Midian",
						"Pethor", "Amaw", "Egypt", "Arnon", "Kirjathhuzoth",
						"Bamothbaal"),
				arrayOf("Moab", "Aram", "Zophim", "Pisgah", "Egypt",
						"Peor"),
				arrayOf("Egypt", "Moab", "Edom", "Seir", "Kain",
						"Asshur", "Chittim"),
				arrayOf("Shittim", "Moab", "Peor", "Midian"),
				arrayOf("Moab", "Jordan", "Jericho", "Egypt",
						"wilderness of Sinai", "Canaan"),
				arrayOf("Abarim", "wilderness of Zin", "Meribah",
						"Kadesh"),
				arrayOf("mount Sinai"),
				arrayOf<String?>(null),
				arrayOf<String?>(null),
				arrayOf("Midian", "Moab", "Jordan", "Jericho", "Peor"),
				arrayOf("Jazer", "Gilead", "Ataroth", "Dibon",
						"Nimrah", "Heshbon", "Elealeh", "Shebam", "Nebo", "Beon",
						"Jordan", "Kadeshbarnea", "valley of Eshcol", "Egypt",
						"Bashan", "Aroer", "Atroth, Shophan", "Jogbehah",
						"Bethnimrah", "Bethharan", "Kiriathaim", "Baalmeon",
						"Shibmah", "Havothjair", "Nobah", "Kenath"),
				arrayOf("Egypt", "Rameses", "Succoth (Egypt)", "Etham",
						"Pihahiroth", "Baalzephon", "Migdol", "Marah", "Elim",
						"Red sea", "wilderness of Sin", "Dophkah", "Alush",
						"Rephidim", "wilderness of Sinai", "Kibrothhattaavah",
						"Hazeroth", "Rithmah", "Rimmonparez", "Libnah", "Rissah",
						"Kehelathah", "mount Shapher", "Haradah", "Makheloth",
						"Tahath", "Terah", "Mithcah", "Hashmonah", "Moseroth",
						"Benejaakan", "Horhagidgad", "Jotbathah", "Ebronah",
						"Eziongaber", "wilderness of Zin", "Kadesh", "mount Hor",
						"Edom", "Arad", "Canaan", "Zalmonah", "Punon", "Oboth",
						"Ijeabarim", "Moab", "Iim", "Dibongad", "Almondiblathaim",
						"Abarim", "Nebo", "Jordan", "Jericho", "Bethjesimoth",
						"Abelshittim"),
				arrayOf("Canaan", "wilderness of Zin", "Edom",
						"salt sea", "Akrabbim", "Zin", "Kadeshbarnea",
						"Hazaraddar", "Azmon", "river of Egypt", "great sea",
						"mount Hor", "Hamath", "Zedad", "Ziphron", "Hazarenan",
						"Shepham", "Riblah", "Ain", "sea of Chinnereth",
						"Jordan", "Jericho"),
				arrayOf("Moab", "Jordan", "Jericho", "Canaan"),
				arrayOf("Gilead", "Moab", "Jordan", "Jericho"))

		private val Deuteronomy = arrayOf(arrayOf("Bashan", "Canaan",
				"Dizahab", "Egypt", "Edrei", "Horeb", "Heshbon", "Hazeroth",
				"Hormah", "Israel", "Jordan", "Kadeshbarnea", "Lebanon", "Laban",
				"mount Seir", "Moab", "Paran", "Red sea", "Tophel",
				"the river Euphrates", "valley of Eshcol", "wilderness"),
				arrayOf("Aroer", "Ammon", "Arnon", "Ar", "Azzah",
						"brook Zered", "Esau", "Eziongaber", "Elath", "Gilead",
                        "Heshbon", "Israel", "Jabbok", "Jordan", "Jahaz",
						"Kedemoth", "Kadeshbarnea", "mount Seir", "Moab",
						"Red sea", "Seir"),
				arrayOf("Aroer", "Ammon", "Arnon", "Argob", "Ar",
						"Bethpeor", "Bashan", "Chinnereth", "Edrei", "Gilead",
						"Geshuri", "Heshbon", "Israel", "Jabbok", "Jair",
						"Jordan", "Lebanon", "mount Hermon", "Pisgah",
						"salt sea", "Sidon"),
				arrayOf("Aroer", "Arnon", "Ar", "Baalpeor", "Bethpeor",
						"Bashan", "Bezer", "Egypt", "Golan", "Gilead", "Horeb",
						"Heshbon", "Israel", "Jordan", "Pisgah", "Ramoth",
						"Sion", "wilderness"),
				arrayOf("Egypt", "Horeb", "Israel"),
				arrayOf("Egypt", "Israel", "Massah"),
				arrayOf("Egypt"),
				arrayOf("Egypt", "wilderness"),
				arrayOf("Egypt", "Horeb", "Israel", "Jordan",
						"Kadeshbarnea", "Kibrothhattaavah", "Massah", "Taberah",
						"wilderness"),
				arrayOf("Beeroth", "Egypt", "Israel"),
				arrayOf("Egypt", "the river Euphrates", "Gilgal",
						"Israel", "Jordan", "Lebanon", "Moreh", "mount Ebal",
						"mount Gerizim", "Red sea", "wilderness"),
				arrayOf("Jordan"),
				arrayOf("Egypt", "Israel"),
				arrayOf<String?>(null),
				arrayOf("Egypt"),
				arrayOf("Egypt"),
				arrayOf("Egypt", "Israel"),
				arrayOf("Horeb", "Israel"),
				arrayOf("Israel"),
				arrayOf("Egypt", "Israel"),
				arrayOf("Israel"),
				arrayOf("Israel"),
				arrayOf("Ammon", "Egypt", "Edom", "Israel", "Moab",
						"Mesopotamia", "Pethor"),
				arrayOf("Egypt", "Israel"),
				arrayOf("Amalek", "Egypt", "Israel"),
				arrayOf("Egypt", "Israel", "Syria"),
				arrayOf("Dan", "Israel", "Jordan", "mount Ebal",
						"mount Gerizim"),
				arrayOf("Egypt"),
				arrayOf("Admah", "Bashan", "Egypt", "Gomorrah",
						"Horeb", "Heshbon", "Israel", "Moab", "Sodom",
                        "wilderness", "Zeboim"),
				arrayOf("Jordan"),
				arrayOf("Israel", "Jordan"),
				arrayOf("Abarim", "Bashan", "Canaan", "Gomorrah",
						"Israel", "Jordan", "Jericho", "Kadesh", "Meribah",
						"mount Hor", "Moab", "mount Nebo", "Nebo", "Sodom",
						"wilderness of Zin"),
				arrayOf("Bashan", "Israel", "Meribah", "mount Paran",
						"Massah", "Sinai", "Seir"),
				arrayOf("Bethpeor", "Dan", "Egypt", "Ephraim",
						"Gilead", "Israel", "Jericho", "Moab", "Nebo", "Pisgah",
						"valley of Jericho", "Zoar"))

		private val Joshua = arrayOf(arrayOf("Jordan", "Israel",
                "the wilderness", "Lebanon", "the river Euphrates", "great sea"),
				arrayOf("Shittim", "Jericho", "Israel", "Jordan",
						"Red sea", "Egypt"),
				arrayOf("Shittim", "Jordan", "Israel", "Adam",
						"salt sea", "Jericho"),
				arrayOf("Jordan", "Israel", "Jericho", "Gilgal",
						"Red sea"),
				arrayOf("Jordan", "Israel", "Egypt", "wilderness",
						"Gilgal", "Jericho", "Canaan"),
				arrayOf("Jericho", "Israel"),
				arrayOf("Ai", "Israel", "Jericho", "Bethaven",
						"Bethel", "Shebarim", "Jordan", "valley of Achor"),
				arrayOf("Ai", "Jericho", "Bethel", "wilderness",
						"Israel", "mount Ebal", "mount Gerizim"),
				arrayOf("Jordan", "great sea", "Lebanon", "Israel",
						"Gibeon", "Jericho", "Ai", "Gilgal", "Egypt", "Heshbon",
						"Bashan", "Ashtaroth", "Chephirah", "Beeroth",
						"Kirjathjearim"),
				arrayOf("Jerusalem", "Ai", "Jericho", "Gibeon",
						"Israel", "Hebron", "Warmth", "Lachish", "Eglon",
						"Gilgal", "Jarmuth", "Azekah", "Makkedah", "Libnah",
						"Gezer", "Kadeshbarnea", "Gaza", "Goshen", "Bethhoron"),
				arrayOf("Anab", "Ashdod", "Achshaph", "Canaan",
						"Chinneroth", "Cana", "Debir", "Dor", "Gaza", "Goshen",
						"Gibeon", "Gath", "Hazor", "Hebron", "Israel", "Lebanon",
						"Merom", "Misrephothmaim", "mount Halak", "Mizpeh",
						"Madon", "mount Hermon", "Shimron", "Seir",
						"valley of Mizpeh"),
				arrayOf("Aroer", "Ammon", "Arad", "Arnon", "Adullam",
						"Ar", "Ashtaroth", "Achshaph", "Aphek", "Bashan",
						"Bethel", "Carmel", "Canaan", "Chinneroth", "Cana",
						"Debir", "Dor", "Edrei", "Eglon", "Gezer", "Gilead",
						"Gilgal", "Geshuri", "Hazor", "Hebron", "Heshbon",
						"Hepher", "Hormah", "Israel", "Jokneam", "Jabbok",
						"Jerusalem", "Jordan", "Jarmuth", "Jericho", "Kedesh",
						"Libnah", "Lebanon", "Lachish", "Megiddo", "Makkedah",
						"mount Halak", "Madon", "mount Hermon", "salt sea",
						"Seir", "Taanach", "Tirzah", "Tappuah", "wilderness"),
				arrayOf("Aroer", "Ammon", "Arnon", "Ar", "Ashtaroth",
						"Aphek", "Bamothbaal", "Bethnimrah", "Betonim", "Bamoth",
						"Bethpeor", "Bashan", "Canaan", "Chinnereth", "Debir",
						"Dibon", "Egypt", "Edrei", "Ekron", "Gilead", "Gaza",
						"Geshur", "Hamath", "Heshbon", "Israel", "Jazer", "Jair",
						"Jordan", "Jahaz", "Jericho", "Kedemoth", "Lebanon",
						"Mephaath", "Misrephothmaim", "Mahanaim", "Moab",
						"Midian", "mount Hermon", "Medeba", "Mearah", "Rama",
						"Ramah", "Rekem", "Sidon", "sea of Chinnereth",
						"Succoth", "Zaphon"),
				arrayOf("Canaan", "Ephraim", "Gilgal", "Hebron",
						"Israel", "Jordan", "Kadeshbarnea", "Kirjatharba",
						"wilderness"),
				arrayOf("Achzib", "Anab", "Amam", "Ain", "Adithaim",
						"Adadah", "Arab", "Adullam", "Azmon", "Ashdod", "Ashan",
						"Adummim", "Ashnah", "Anim", "Aphek", "Azekah",
						"Beersheba", "Bethdagon", "Bethtappuah", "Beer",
						"Bozkath", "Betharabah", "river of Egypt", "Bethzur",
						"Bethanoth", "Baalah", "Bethshemesh", "Carmel",
						"Chesalon", "Chesil", "Cabbon", "Dannah", "Debir",
						"Dumah", "Dilean", "Dimonah", "Dan", "Egypt", "Ether",
						"Eltolad", "Ephron", "Enshemesh", "Engannim", "Eshtaol",
						"Eltekon", "Enrogel", "Ekron", "Engedi", "Hazazontamar",
						"Hazezontamar", "Edom", "Enam", "Eglon", "Gederoth",
						"Gilgal", "great sea", "Gedor", "Gaza", "Goshen",
						"Giloh", "Gibeah", "Gederothaim", "Gederah", "Hazor",
						"Hazargaddah", "Hebron", "Humtah", "Hadashah", "Holon",
						"Halhul", "Hazarshual", "Hormah", "Heshmon", "Ithnan",
						"Iim", "Jerusalem", "Joktheel", "Jabneel", "Jokdeam",
						"Juttah", "Jattir", "Jezreel", "Jagur", "Jordan",
						"Jarmuth", "Kinah", "Kadesh", "Kabzeel", "Kedesh",
						"Kadeshbarnea", "Karkaa", "Keilah", "Kirjatharba",
						"Kirjathjearim", "Libnah", "Lebaoth", "Lachish",
						"Lahmam", "Mareshah", "Madmannah", "Makkedah",
						"Migdalgad", "mount Seir", "Maon", "Mizpeh", "Moladah",
						"mount Ephron", "Maarath", "mount Baalah", "Middin",
						"Nezib", "Naamah", "Nibshan", "Nephtoah", "Rimmon",
						"salt sea", "Secacah", "Sansannah", "Shema", "Shamir",
						"Socoh", "Seir", "Telem", "Timnah", "Tappuah",
						"valley of Hinnom", "valley of Achor", "wilderness of Zin",
						"Zior", "Zanoah", "Zin", "Ziph", "Zenan", "Ziklag"),
				arrayOf("Atarothaddar", "Ataroth", "Bethel",
						"Bethhoron", "Canaan", "Ephraim", "Gezer", "Jordan",
						"Jericho", "Kanah", "Luz", "Tappuah", "Taanathshiloh",
						"wilderness"),
				arrayOf("Bashan", "Canaan", "Dor", "Ephraim", "Endor",
						"Gilead", "Hepher", "Israel", "Ibleam", "Jezreel",
						"Jordan", "Kanah", "Megiddo", "Shechem", "Taanach",
						"Tirzah", "Tappuah", "valley of Jezreel"),
				arrayOf("Arabah", "Ataroth", "Atarothadar", "Arab",
						"Ar", "Adummim", "Beer", "Beeroth", "Bethhoglah",
						"Betharabah", "Bethel", "Bethaven", "Chephirah",
						"Enshemesh", "Enrogel", "Gibeon", "Israel", "Irpeel",
						"Jerusalem", "Jordan", "Jericho", "Kirjathjearim",
						"Luz", "Mizpeh", "Mozah", "Nephtoah", "Ophni", "Ophrah",
						"Rama", "Ramah", "Rekem", "salt sea", "Shiloh",
						"Taralah", "valley of Hinnom", "Zemaraim"),
				arrayOf("Achzib", "Ain", "Amad", "Aznothtabor",
						"Anaharath", "Adamah", "Ashan", "Achshaph", "Aphek",
						"Beersheba", "Bethlebaoth", "Bethdagon", "Beer",
						"Beneberak", "Bethemek", "Bethpazzez", "Bethlehem",
						"Beten", "Bethanath", "Bethul", "Baalathbeer", "Balah",
						"Baalath", "Bethshemesh", "Carmel", "Chesulloth",
						"Cabul", "Chinnereth", "Daberath", "Dan", "Edrei",
						"Ether", "Ephraim", "Eltolad", "Engannim", "Eshtaol",
						"Elon", "Ekron", "Enhaddah", "Eltekeh", "Enhazor",
						"Gathrimmon", "Gibbethon", "Gath", "Horem", "Hazor",
						"Hannathon", "Hammath", "Hebron", "Hali", "Heleph",
						"Helkath", "Hosah", "Hazarshual", "Hormah", "Hazarsusah",
						"Hukkok", "Israel", "Idalah", "Japhia", "Jokneam",
						"Jabneel", "Jehud", "Jezreel", "Jordan", "Kanah",
						"Kishion", "Kedesh", "Moladah", "Mejarkon", "Migdalel",
						"Neiel", "Rehob", "Remeth", "Rakkon", "Rabbith",
						"Shihorlibnath", "Shiloh", "Shimron", "Sharuhen",
						"Sheba", "Shunem", "Sarid", "Tabor", "Tyre", "Ummah",
						"Ziddim", "Zaanan", "Zer", "Zorah", "Zaanannim",
						"Ziklag"),
				arrayOf("Bashan", "Bezer", "Ephraim", "Golan",
						"Gilead", "Galilee", "Hebron", "Israel", "Jordan",
						"Jericho", "Kedesh", "Kirjatharba", "Ramoth", "Shechem"),
				arrayOf("Aijalon", "Anathoth", "Ain", "Abdon",
						"Bashan", "Bezer", "Bethshemesh", "Canaan", "Dimnah",
						"Debir", "Dan", "Ephraim", "Engannim", "Eltekeh",
						"Golan", "Gezer", "Gilead", "Gathrimmon", "Gibeon",
						"Gibbethon", "Galilee", "Geba", "Gath", "Hebron",
						"Heshbon", "Helkath", "Holon", "Israel", "Jokneam",
						"Jazer", "Juttah", "Jattir", "Jarmuth", "Jahaz",
						"Kibzaim", "Kartan", "Kedemoth", "Kishon", "Kedesh",
						"Libnah", "Mephaath", "Mishal", "Mahanaim", "Rehob",
						"Ramoth", "Shechem", "Shiloh"),
				arrayOf("Bashan", "Canaan", "Gilead", "Israel",
						"Jordan", "Peor", "Shiloh"),
				arrayOf("great sea", "Israel", "Jordan"),
				arrayOf("Canaan", "Egypt", "Ephraim", "Esau", "Gaash",
						"Israel", "Jordan", "Jericho", "mount Seir", "Moab",
						"Red sea", "Shechem", "wilderness"))

		private val Judges = arrayOf(arrayOf("Aijalon", "Akrabbim",
				"Achzib", "Arad", "Ar", "Ahlab", "Bezek", "Bethanath", "Bethel",
				"Bethshemesh", "Canaan", "Debir", "Dor", "Dan", "Ephraim",
				"Ekron", "Gezer", "Gaza", "Helbah", "Heres", "Hebron", "Hormah",
				"Israel", "Ibleam", "Jerusalem", "Kitron", "Kirjatharba", "Luz",
				"Megiddo", "Nahalol", "Rehob", "Shaalbim", "Taanach",
				"the wilderness", "Zephath"),
				arrayOf("Ashtaroth", "Egypt", "Ephraim", "Gilgal",
						"Gaash", "Israel", "Timnathheres"),
				arrayOf("Ammon", "Amalek", "Canaan", "Ephraim",
						"Eglon", "Gilgal", "Hamath", "Israel", "Jordan",
						"Lebanon", "Moab", "Mesopotamia", "mount Lebanon",
						"Sidon"),
				arrayOf("Bethel", "Canaan", "Ephraim", "Hazor",
						"Israel", "Kishon", "Kedesh", "mount Tabor"),
				arrayOf("Amalek", "Canaan", "Dan", "Ephraim", "Edom",
						"Gilead", "Israel", "Jordan", "Kishon", "Meroz",
						"Megiddo", "Sinai", "Seir", "Taanach"),
				arrayOf("Amalek", "Egypt", "Gaza", "Israel", "Midian",
						"Ophrah", "valley of Jezreel"),
				arrayOf("Abelmeholah", "Amalek", "Bethshittah",
						"Ephraim", "Gilead", "Harod", "Israel", "Jordan",
						"Moreh", "Midian", "Tabbath"),
				arrayOf("Ephraim", "Israel", "Jordan", "Jogbehah",
						"Karkor", "Midian", "Nob", "Nobah", "Ophrah", "Penuel",
						"Shechem", "Succoth", "Tabor", "wilderness"),
				arrayOf("Arumah", "Beer", "Israel", "Lebanon",
						"Midian", "mount Gerizim", "Millo", "Ophrah", "Shechem",
						"Thebez"),
				arrayOf("Ammon", "Amalek", "Ashtaroth", "Egypt",
						"Ephraim", "Gilead", "Havothjair", "Israel", "Jordan",
						"Maon", "Moab", "Mizpeh", "Syria", "Shamir"),
				arrayOf("Aroer", "Ammon", "Arnon", "Egypt", "Edom",
						"Gilead", "Heshbon", "Israel", "Jabbok", "Jordan",
						"Jahaz", "Kadesh", "Minnith", "Minni", "Moab", "Mizpeh",
						"Red sea", "Tob", "wilderness"),
				arrayOf("Aijalon", "Ammon", "Amalek", "Ar",
						"Bethlehem", "Ephraim", "Gilead", "Israel", "Jordan",
						"Pirathon"),
				arrayOf("Dan", "Eshtaol", "Israel", "Zorah"),
				arrayOf("Ashkelon", "Israel", "Timnath"),
				arrayOf("Etam", "Enhakkore", "Israel", "Lehi",
						"Ramathlehi"),
				arrayOf("Eshtaol", "Gaza", "Hebron", "Israel",
						"valley of Sorek", "Zorah"),
				arrayOf("Bethlehemjudah", "Ephraim", "Israel"),
				arrayOf("Bethrehob", "Dan", "Ephraim", "Eshtaol",
						"Israel", "Mahanehdan", "Shiloh", "Zorah"),
				arrayOf("Bethlehemjudah", "Egypt", "Ephraim",
						"Gibeah", "Israel", "Jerusalem", "Rama", "Ramah"),
				arrayOf("Beersheba", "Beer", "Baaltamar", "Dan",
						"Gidom", "Gilead", "Gibeah", "Israel", "Mizpeh",
						"Rimmon", "the wilderness"),
				arrayOf("Bethel", "Canaan", "Israel", "Jabeshgilead",
						"Lebonah", "Mizpeh", "Rimmon", "Shechem", "Shiloh"))

		private val Ruth = arrayOf(arrayOf("Bethlehem",
				"Bethlehemjudah", "Ephrath", "Moab"),
				arrayOf("Bethlehem", "Israel", "Moab"),
				arrayOf<String?>(null),
				arrayOf("Bethlehem", "Israel", "Moab"))

		private val First_Samuel = arrayOf(arrayOf("Ephraim",
				"Ephrath", "Israel", "Rama", "Ramah", "Shiloh"),
				arrayOf("Egypt", "Israel", "Rama", "Ramah", "Shiloh"),
				arrayOf("Beersheba", "Beer", "Dan", "Israel",
						"Shiloh"),
				arrayOf("Aphek", "Egypt", "Ebenezer", "Israel",
						"Shiloh", "wilderness"),
				arrayOf("Ashdod", "Ebenezer", "Ekron", "Gath",
						"Israel"),
				arrayOf("Ashdod", "Askelon", "Bethshemesh", "Egypt",
						"Ekron", "Gaza", "Gath", "Israel", "Kirjathjearim"),
				arrayOf("Ashtaroth", "Bethcar", "Bethel", "Ebenezer",
						"Ekron", "Gilgal", "Gath", "Israel", "Kirjathjearim",
						"Mizpeh", "Rama", "Ramah", "Shen"),
				arrayOf("Beersheba", "Beer", "Egypt", "Israel", "Rama",
						"Ramah"),
				arrayOf("Ephraim", "Israel", "Zuph"),
				arrayOf("Bethel", "Egypt", "Gilgal", "Gibeah",
						"Israel", "Mizpeh", "Tabor", "Zelzah"),
				arrayOf("Ammon", "Bezek", "Gilgal", "Gibeah", "Israel",
						"Jabeshgilead"),
				arrayOf("Ammon", "Ashtaroth", "Egypt", "Hazor",
						"Israel", "Moab"),
				arrayOf("Bethel", "Bethaven", "Bethhoron", "Gilead",
						"Gilgal", "Gibeah", "Geba", "Israel", "Jordan",
						"Michmash", "Ophrah", "Shual", "valley of Zeboim",
						"the wilderness", "Zeboim"),
				arrayOf("Aijalon", "Ammon", "Amalek", "Bozez",
						"Bethaven", "Ephraim", "Edom", "Gibeah", "Israel",
						"Michmash", "Moab", "Migron", "Seneh", "Shiloh",
						"Zobah"),
				arrayOf("Amalek", "Carmel", "Egypt", "Gilgal",
						"Gibeah", "Havilah", "Israel", "Rama", "Ramah", "Shur",
                        "Telaim"),
                arrayOf("Bethlehem", "Israel", "Rama", "Ramah"),
				arrayOf("Azekah", "Bethlehem", "Bethlehemjudah",
						"Ephrath", "Ephesdammim", "Ekron", "Gath", "Israel",
						"Jerusalem", "Shaaraim", "valley of Elah",
						"the wilderness"),
				arrayOf("Israel"),
				arrayOf("Israel", "Naioth", "Rama", "Ramah"),
				arrayOf("Bethlehem", "Israel", "Naioth", "Rama",
						"Ramah"),
				arrayOf("Edom", "Gath", "Nob", "valley of Elah"),
				arrayOf("Adullam", "Edom", "Gibeah", "Moab", "Mizpeh",
						"Nob", "Rama", "Ramah"),
				arrayOf("Engedi", "Hazazontamar", "Hazezontamar",
						"Gibeah", "Hachilah", "Israel", "Jeshimon", "Keilah",
						"Maon", "the wilderness", "Ziph"),
				arrayOf("Engedi", "Hazazontamar", "Hazezontamar",
						"Israel"),
				arrayOf("Carmel", "Gallim", "Israel", "Jezreel",
						"Maon", "Rama", "Ramah", "wilderness of Paran"),
				arrayOf("Gibeah", "Hachilah", "Israel", "Jeshimon",
						"Ziph"),
				arrayOf("Amalek", "Carmel", "Egypt", "Geshur", "Gath",
						"Israel", "Jezreel", "Shur", "Ziklag"),
				arrayOf("Amalek", "Endor", "Gilboa", "Israel", "Rama",
						"Ramah", "Shunem"),
				arrayOf("Aphek", "Israel", "Jezreel"),
				arrayOf("Aroer", "Amalek", "Besor", "Bethel",
						"Carmel", "Egypt", "Hebron", "Hormah", "Israel",
						"Jattir", "Jezreel", "Ramoth", "Siphmoth", "Ziklag"),
				arrayOf("Ashtaroth", "Bethshan", "Israel",
						"Jabeshgilead", "Jordan", "mount Gilboa"))

		private val Second_Samuel = arrayOf(arrayOf("Amalek", "Gilboa",
				"Gath", "Israel", "mount Gilboa", "Ziklag"),
				arrayOf("Ammah", "Bethlehem", "Carmel", "Ephraim",
						"Giah", "Gilead", "Gibeon", "Hebron", "Helkath",
						"Helkathhazzurim", "Israel", "Jabeshgilead", "Jezreel",
						"Jordan", "Mahanaim"),
				arrayOf("Beersheba", "Beer", "Bahurim", "Carmel",
						"Dan", "Gibeon", "Geshur", "Hebron", "Israel", "Jezreel",
						"Maacah", "Sirah"),
				arrayOf("Beer", "Beeroth", "Gittaim", "Hebron",
						"Israel", "Jezreel", "Rimmon", "Ziklag"),
				arrayOf("Baalperazim", "Geba", "Hebron", "Israel",
						"Japhia", "Jerusalem", "Millo", "Rephaim", "Tyre",
						"valley of Rephaim"),
				arrayOf("Gibeah", "Israel", "Perezuzzah"),
				arrayOf("Egypt", "Israel"),
				arrayOf("Ammon", "Amalek", "Betah", "Damascus",
						"Euphrates", "Edom", "Hamath", "Israel", "Jerusalem",
						"Moab", "Rehob", "Syria", "Zobah"),
				arrayOf("Jerusalem", "Lod", "Lodebar"),
				arrayOf("Ammon", "Bethrehob", "Helam", "Israel",
						"Jerusalem", "Jordan", "Jericho", "Maacah", "Rehob",
						"Syria"),
				arrayOf("Ammon", "Israel", "Jerusalem", "Thebez"),
				arrayOf("Ammon", "Israel", "Jerusalem"),
				arrayOf("Baalhazor", "Ephraim", "Geshur", "Israel"),
				arrayOf("Geshur", "Israel", "Jerusalem", "Tamar",
						"Tekoah"),
				arrayOf("Giloh", "Geshur", "Gath", "Hebron", "Israel",
						"Jerusalem", "Kidron", "Syria", "wilderness"),
				arrayOf("Bahurim", "Israel", "Jerusalem", "wilderness"),
				arrayOf("Ammon", "Beersheba", "Beer", "Bahurim", "Dan",
						"Enrogel", "Gilead", "Israel", "Jerusalem", "Jordan",
						"Lodebar", "Mahanaim", "Rogelim", "wilderness"),
				arrayOf("Ephraim", "Israel", "king\'s dale"),
				arrayOf("Bahurim", "Gilead", "Gilgal", "Israel",
						"Jerusalem", "Jordan", "Mahanaim", "Rogelim"),
				arrayOf("Ephraim", "Gibeon", "Israel", "Jerusalem",
						"Jair", "Jordan"),
				arrayOf("Bethshan", "Bethlehem", "Gilboa", "Gibeon",
						"Gibeah", "Gath", "Israel", "Jabeshgilead"),
				arrayOf<String?>(null),
                arrayOf("Ammon", "Adullam", "Beer", "Beeroth",
						"Bethlehem", "Carmel", "Egypt", "Gareb", "Gibeah",
						"Gaash", "Hara", "Harod", "Israel", "Kabzeel", "Moab",
						"Pirathon", "Rephaim", "valley of Rephaim", "Zobah"),
				arrayOf("Aroer", "Beersheba", "Beer", "Canaan", "Dan",
						"Gilead", "Israel", "Jerusalem", "Jazer", "Jordan",
						"Tyre"))

		private val First_Kings = arrayOf(arrayOf("Enrogel", "Gihon",
				"Israel"),
				arrayOf("Anathoth", "Bahurim", "Gilead", "Gath",
						"Hebron", "Israel", "Jerusalem", "Jordan", "Kidron",
						"Mahanaim", "Shiloh"),
				arrayOf("Egypt", "Gibeon", "Israel", "Jerusalem"),
				arrayOf("Abelmeholah", "Argob", "Beersheba", "Beer",
						"Bashan", "Bethshemesh", "Dor", "Dan", "Egypt",
						"Ephraim", "Elon", "Elonbethhanan", "Gilead", "Hepher",
						"Israel", "Jokneam", "Jair", "Jezreel", "Lebanon",
						"Megiddo", "Mahanaim", "Makaz", "Ramoth", "Ramothgilead",
						"Shaalbim", "Tiphsah", "Taanach"),
				arrayOf("Israel", "Lebanon", "Sidon", "Tyre"),
				arrayOf("Egypt", "Israel", "temple"),
				arrayOf("Jordan", "Lebanon", "plain of Jordan",
						"Succoth", "temple", "Tyre"),
				arrayOf("river of Egypt", "Egypt", "Hamath", "Horeb",
						"Israel", "Jerusalem"),
				arrayOf("Baalath", "Canaan", "Cabul", "Egypt", "Edom",
						"Gezer", "Gibeon", "Galilee", "Hazor", "Israel",
						"Jerusalem", "Lebanon", "Megiddo", "Millo", "Ophir",
						"Red sea", "Tadmor", "Tyre"),
				arrayOf("Arabia", "Egypt", "Israel", "Jerusalem",
						"Lebanon", "Ophir", "Syria", "Sheba"),
				arrayOf("Ammon", "Damascus", "Egypt", "Ephrath",
						"Edom", "Israel", "Jerusalem", "Moab", "Midian", "Millo",
						"Syria", "Zobah"),
				arrayOf("Bethel", "Dan", "Egypt", "Ephraim", "Israel",
						"Jerusalem", "Penuel", "Shechem"),
				arrayOf("Bethel", "Samaria"),
				arrayOf("Ammon", "Egypt", "Israel", "Jerusalem",
						"Naamah", "Rehob", "Shiloh", "Tirzah"),
				arrayOf("Damascus", "Dan", "Gibbethon", "Geba",
						"Israel", "Ijon", "Jerusalem", "Kidron", "Mizpah",
						"Rama", "Ramah", "Syria", "Tirzah"),
				arrayOf("Bethel", "Gibbethon", "Israel", "Jericho",
						"Samaria", "Tirzah"),
				arrayOf("Cherith", "Gilead", "Israel", "Jordan",
						"Zarephath"),
				arrayOf("Carmel", "Israel", "Jezreel", "Kishon",
						"mount Carmel", "Samaria"),
				arrayOf("Abelmeholah", "Beersheba", "Beer", "Damascus",
						"Horeb", "Israel", "Syria"),
				arrayOf("Aphek", "Damascus", "Israel", "Syria",
						"Samaria"),
				arrayOf("Israel", "Jezreel", "Samaria"),
				arrayOf("Edom", "Gilead", "Israel", "Jerusalem",
						"Ophir", "Ramoth", "Ramothgilead", "Syria", "Samaria"))

		private val Second_Kings = arrayOf(arrayOf("Ekron", "Israel",
				"Moab", "Samaria"),
                arrayOf("Bethel", "Carmel", "Gilgal", "Israel",
                        "Jordan", "Jericho", "mount Carmel", "Samaria"),
				arrayOf("Edom", "Israel", "Moab", "Samaria",
						"wilderness"),
				arrayOf("Gilgal", "mount Carmel", "Shunem"),
                arrayOf("Abana", "Damascus", "Ephraim", "Israel",
						"Jordan", "Pharpar", "Rimmon", "Syria", "Samaria"),
				arrayOf("Dothan", "Israel", "Jordan", "Syria",
						"Samaria"),
				arrayOf("Egypt", "Israel", "Jordan", "Syria",
						"Samaria"),
                arrayOf("Damascus", "Edom", "Israel", "Jerusalem",
                        "Jezreel", "Libnah", "Rama", "Ramah", "Ramoth",
						"Ramothgilead", "Syria"),
				arrayOf("Gur", "Israel", "Ibleam", "Jerusalem",
						"Jezreel", "Megiddo", "Ramoth", "Ramothgilead", "Syria"),
				arrayOf("Aroer", "Arnon", "Bashan", "Bethel", "Dan",
						"Gilead", "Israel", "Jezreel", "Jordan", "Samaria"),
				arrayOf("Sur", "temple"),
				arrayOf("Beersheba", "Beer", "Gath", "Jerusalem",
						"Millo", "Syria", "Silla"),
				arrayOf("Aphek", "Israel", "Moab", "Syria", "Samaria"),
				arrayOf("Bethshemesh", "Damascus", "Ephraim", "Elath",
						"Edom", "Gathhepher", "Gath", "Hamath", "Israel",
						"Jerusalem", "Joktheel", "Lebanon", "Lachish",
						"Samaria"),
				arrayOf("Assyria", "Argob", "Gilead", "Galilee",
						"Hazor", "Israel", "Ijon", "Jerusalem", "Janoah",
						"Kedesh", "Syria", "Samaria", "Tiphsah", "Tirzah"),
				arrayOf("Assyria", "Damascus", "Elath", "Israel",
						"Jerusalem", "Syria"),
				arrayOf("Assyria", "Babylon", "Bethel", "Egypt",
						"Gozan", "Hamath", "Halah", "Habor", "Israel", "Samaria",
						"Sepharvaim", "Sephar"),
				arrayOf("Assyria", "Arpad", "Egypt", "Gozan", "Gaza",
						"Hamath", "Halah", "Hena", "Habor", "Israel",
						"Jerusalem", "Lachish", "Syria", "Samaria", "Sepharvaim",
						"Sephar", "temple"),
				arrayOf("Assyria", "Arpad", "Carmel", "Ethiopia",
						"Gozan", "Hara", "Hamath", "Haran", "Hena", "Israel",
						"Jerusalem", "Libnah", "Lebanon", "Lachish",
						"mount Zion", "Nineveh", "Rezeph", "Sepharvaim",
						"Sephar"),
				arrayOf("Assyria", "Babylon"),
				arrayOf("Egypt", "Israel", "Jerusalem", "Jotbah",
						"Samaria", "Uzza"),
				arrayOf("Israel", "Jerusalem"),
				arrayOf("Ammon", "Assyria", "Beersheba", "Beer",
						"Bethel", "Egypt", "Euphrates", "Geba", "Hamath",
						"Israel", "Jerusalem", "Kidron", "Libnah", "Megiddo",
						"Moab", "Riblah", "Samaria", "temple"),
				arrayOf("Ammon", "river of Egypt", "Babylon", "Egypt",
						"Euphrates", "Israel", "Jerusalem", "Libnah", "Moab",
						"Syria", "temple"),
				arrayOf("Babylon", "Egypt", "Hamath", "Jerusalem",
						"Jericho", "Mizpah", "Riblah"))

		private val First_Chronicles = arrayOf(arrayOf<String?>(null),
				arrayOf<String?>(null),
                arrayOf("Hebron", "Jerusalem"),
				arrayOf("Ain", "Amalek", "Ashan", "Beersheba",
						"Bethuel", "Beer", "Bilhah", "Bethlehem", "Ezem", "Etam",
						"Gedor", "Hepher", "Hazarsusim", "Hazarshual", "Hormah",
						"Israel", "Jehud", "Jezreel", "Jabez", "Keilah",
						"Mareshah", "mount Seir", "Moab", "Moladah", "Ophrah",
						"Penuel", "Rimmon", "Shaaraim", "Seir", "Tochen",
						"Tekoa", "Tolad", "Zanoah", "Ziph", "Ziklag"),
				arrayOf("Aroer", "Assyria", "Baalmeon", "Bashan",
						"Buz", "Bela", "Euphrates", "Gozan", "Gilead", "Gog",
						"Hara", "Halah", "Habor", "Israel", "Jetur",
						"mount Hermon", "Nebo", "Nodab", "Pul", "Sheba",
						"wilderness"),
				arrayOf("Aijalon", "Anathoth", "Alemeth", "Abdon",
						"Ashan", "Ashtaroth", "Bashan", "Bezer", "Bethshemesh",
						"Debir", "Daberath", "Ephraim", "Golan", "Gezer",
						"Gilead", "Gathrimmon", "Galilee", "Geba", "Gath",
						"Hebron", "Heshbon", "Ham", "Israel", "Jerusalem",
						"Jazer", "Jattir", "Jordan", "Jericho", "Kedemoth",
						"Kedesh", "Libnah", "Mephaath", "Mahanaim", "Mashal",
						"Rehob", "Ramoth", "Rimmon", "Shechem", "temple",
						"Tabor", "Uzza", "wilderness", "Zuph"),
				arrayOf("Anathoth", "Aram", "Bered", "Bilhah", "Bela",
						"Bezer", "Bethel", "Dor", "Ephraim", "Gezer", "Gilead",
						"Gaza", "Gath", "Israel", "Megiddo", "Naaran", "Shechem",
						"Shual", "Tahath", "Taanach"),
				arrayOf("Aijalon", "Addar", "Arad", "Alemeth",
						"Abdon", "Bela", "Elam", "Gedor", "Gibeon", "Geba",
						"Gath", "Jerusalem", "Lod", "Mesha", "Moab", "Manahath",
						"Ono", "Penuel", "Shema", "Uzza"),
				arrayOf("Abdon", "Babylon", "Ephraim", "Gedor",
						"Gibeon", "Israel", "Immer", "Jerusalem", "Zimri"),
				arrayOf("Israel", "Jabeshgilead", "mount Gilboa",
						"temple"),
				arrayOf("Aroer", "Ammon", "Adullam", "Baharum",
						"Bethlehem", "Carmel", "Egypt", "Gareb", "Gibeah",
						"Gaash", "Hara", "Hebron", "Hepher", "Israel",
						"Jerusalem", "Kabzeel", "Moab", "Millo", "Pirathon",
						"Rephaim", "valley of Rephaim"),
				arrayOf("Dan", "Ephraim", "Gedor", "Gibeon", "Hebron",
						"Israel", "Jordan", "wilderness", "Ziklag"),
				arrayOf("Baalah", "Egypt", "Israel", "Kirjathjearim",
						"Perezuzza"),
				arrayOf("Baalperazim", "Gibeon", "Israel", "Jerusalem",
						"Rephaim", "Tyre", "valley of Rephaim"),
				arrayOf("Hebron", "Israel", "Jerusalem"),
				arrayOf("Canaan", "Gibeon", "Israel"),
				arrayOf("Egypt", "Israel"),
				arrayOf("Ammon", "Amalek", "Damascus", "Euphrates",
						"Edom", "Gath", "Hamath", "Israel", "Jerusalem", "Moab",
						"Syria", "Tibhath", "Zobah"),
				arrayOf("Ammon", "Israel", "Jerusalem", "Jordan",
						"Jericho", "Mesopotamia", "Medeba", "Syria", "Zobah"),
				arrayOf("Ammon", "Gezer", "Gath", "Israel",
						"Jerusalem"),
				arrayOf("Beersheba", "Beer", "Dan", "Gibeon", "Israel",
						"Jerusalem", "wilderness"),
				arrayOf("Israel", "Tyre"),
				arrayOf("Hebron", "Israel", "Jerusalem"),
				arrayOf("Israel"),
				arrayOf<String?>(null),
				arrayOf("Gilead", "Hebron", "Israel", "Jordan",
						"Shallecheth"),
                arrayOf("Dan", "Ephraim", "Gilead", "Israel",
						"Pirathon", "Rama", "Ramah"),
				arrayOf("Israel", "Jerusalem"),
				arrayOf("Hebron", "Israel", "Jerusalem", "Ophir"))

		private val Second_Chronicles = arrayOf(arrayOf("Egypt",
                "Gibeon", "Israel", "Jerusalem", "Syria", "wilderness"),
				arrayOf("Dan", "Israel", "Jerusalem", "Joppa",
						"Lebanon", "Tyre"),
				arrayOf("Jerusalem", "Moriah", "temple"),
				arrayOf("plain of Jordan", "Succoth", "temple"),
				arrayOf("Egypt", "Horeb", "Israel", "Jerusalem"),
				arrayOf("Egypt", "Israel", "Jerusalem"),
				arrayOf("river of Egypt", "Egypt", "Hamath", "Israel"),
				arrayOf("Baalath", "Edom", "Hamath", "Israel",
						"Jerusalem", "Lebanon", "Ophir", "Tadmor"),
				arrayOf("Arabia", "Egypt", "Israel", "Jerusalem",
						"Lebanon", "Ophir", "Sheba", "Tarshish"),
				arrayOf("Egypt", "Israel", "Jerusalem", "Shechem"),
				arrayOf("Aijalon", "Adullam", "Adoraim", "Azekah",
						"Bethzur", "Bethlehem", "Etam", "Gath", "Hebron",
						"Israel", "Jerusalem", "Lachish", "Mareshah", "Tekoa",
						"Ziph", "Zorah"),
				arrayOf("Ammon", "Egypt", "Ethiopia", "Israel",
						"Jerusalem"),
				arrayOf("Bethel", "Ephraim", "Gibeah", "Israel",
						"Jerusalem", "Jeshanah", "Zemaraim"),
				arrayOf("Ethiopia", "Gerar", "Jerusalem", "Mareshah",
						"valley of Zephathah"),
				arrayOf("Ephraim", "Israel", "Jerusalem", "Kidron"),
				arrayOf("Damascus", "Dan", "Ethiopia", "Geba",
						"Israel", "Ijon", "Mizpah", "Rama", "Ramah", "Syria"),
				arrayOf("Arabia", "Ephraim", "Israel", "Jerusalem"),
				arrayOf("Israel", "Ramothgilead", "Syria", "Samaria"),
				arrayOf("Beersheba", "Ephraim", "Israel", "Jerusalem"),
				arrayOf("Ammon", "Egypt", "Eziongaber", "Engedi",
						"Hazazontamar", "Hazezontamar", "Israel", "Jerusalem",
						"Jeruel", "Mareshah", "mount Seir", "Moab", "Syria",
						"Seir", "Tekoa", "Tarshish", "Ziz"),
				arrayOf("Arabia", "Ethiopia", "Edom", "Israel",
						"Jerusalem", "Libnah"),
				arrayOf("Arabia", "Israel", "Jerusalem", "Jezreel",
						"Rama", "Ramah", "Ramothgilead", "Syria", "Samaria"),
				arrayOf("Israel", "Jerusalem", "temple"),
				arrayOf("Ammon", "Beersheba", "Beer", "Damascus",
						"Israel", "Jerusalem", "Moab", "Syria", "wilderness"),
				arrayOf("Bethshemesh", "Ephraim", "Edom", "Israel",
						"Jerusalem", "Lebanon", "Lachish", "Samaria", "Seir"),
				arrayOf("Ammon", "Arabia", "Ashdod", "Carmel", "Egypt",
						"Gurbaal", "Gath", "Jerusalem", "temple"),
				arrayOf("Ammon", "Israel", "Jerusalem", "Ophel",
						"temple"),
				arrayOf("Assyria", "Bethshemesh", "Damascus",
						"Ephraim", "Edom", "Gederoth", "Gimzo", "Israel",
						"Jerusalem", "Jericho", "Syria", "Samaria", "Timnah"),
				arrayOf("Israel", "Jerusalem", "Kidron", "temple"),
				arrayOf("Assyria", "Beersheba", "Dan", "Ephraim",
						"Israel", "Jerusalem", "Kidron"),
				arrayOf("Ephraim", "Israel", "Jerusalem"),
				arrayOf("Assyria", "Babylon", "Gihon", "Israel",
						"Jerusalem", "Lachish", "Millo"),
				arrayOf("Assyria", "Babylon", "Gihon", "Israel",
						"Jerusalem", "Ophel"),
				arrayOf("Ephraim", "Israel", "Jerusalem"),
				arrayOf("Egypt", "Euphrates", "Israel", "Jerusalem",
						"Megiddo", "temple"),
				arrayOf("Babylon", "Egypt", "Israel", "Jerusalem",
						"Persia", "temple"))

		private val Ezra = arrayOf(arrayOf("Babylon", "Israel",
				"Jerusalem", "Persia"),
				arrayOf("Ai", "Anathoth", "Beeroth", "Bethlehem",
						"Babylon", "Bethel", "Chephirah", "Cherub", "Elam",
						"Gilead", "Hadid", "Israel", "Immer", "Jerusalem",
						"Jericho", "Lod", "Netophah", "Nebo", "Ono", "Rama",
						"Ramah", "Telmelah", "Uzza"),
				arrayOf("Israel", "Jerusalem", "Joppa", "Lebanon",
						"Persia", "temple", "Tyre", "Zidon"),
				arrayOf("Babylon", "Elam", "Israel", "Jerusalem",
						"Persia", "Syria", "Samaria", "Susa", "temple"),
                arrayOf("Babylon", "Chaldea", "Israel", "Jerusalem",
						"temple"),
				arrayOf("Assyria", "Babylon", "Israel", "Jerusalem",
						"Persia", "temple"),
				arrayOf("Babylon", "Israel", "Jerusalem", "Persia"),
				arrayOf("Ahava", "Babylon", "Casiphia", "Elam",
						"Israel", "Jerusalem", "Jeshua"),
				arrayOf("Ammon", "Canaan", "Egypt", "Israel",
						"Jerusalem", "Moab", "Persia"),
				arrayOf("Israel", "Jerusalem"))

		private val Nehemiah = arrayOf(arrayOf("Israel", "Jerusalem"),
				arrayOf("Ammon", "Arabia", "Israel", "Jerusalem"),
				arrayOf("Bethzur", "Gibeon", "Immer", "Jerusalem",
						"Jericho", "Jeshua", "Keilah", "Mizpah", "Ophel",
						"Zanoah"),
				arrayOf("Ammon", "Arabia", "Ashdod", "Jerusalem",
						"Samaria"),
				arrayOf<String?>(null),
				arrayOf("Arabia", "Jerusalem", "Ono", "temple"),
				arrayOf("Ai", "Anathoth", "Beeroth", "Bethlehem",
						"Babylon", "Bethel", "Bethazmaveth", "Chephirah",
						"Cherub", "Gilead", "Gibeon", "Hadid", "Israel",
                        "Immer", "Jerusalem", "Jericho", "Kirjathjearim", "Lod",
						"Netophah", "Nebo", "Ono", "Rama", "Ramah", "Telmelah",
						"Uzza"),
				arrayOf("Ephraim", "Israel", "Jerusalem"),
				arrayOf("Assyria", "Bashan", "Canaan", "Egypt",
						"Heshbon", "Israel", "mount Sinai", "Red sea",
						"Ur of the Chaldees", "wilderness"),
				arrayOf("Israel"),
				arrayOf("Anathoth", "Ananiah", "Adullam", "Azekah",
						"Beersheba", "Beer", "Bethel", "Dibon", "Geba",
						"Gittaim", "Hazor", "Hadid", "Hazarshual", "Israel",
						"Jerusalem", "Jarmuth", "Jekabzeel", "Jeshua",
						"Kirjatharba", "Lod", "Lachish", "Michmash", "Moladah",
						"Nob", "Neballat", "Ophel", "Ono", "Rama", "Ramah",
						"valley of Hinnom", "Zanoah", "Zeboim", "Ziklag"),
				arrayOf("Ephraim", "Elam", "Gilgal", "Geba", "Israel",
						"Jerusalem", "Persia"),
				arrayOf("Ammon", "Ashdod", "Babylon", "Israel",
						"Jerusalem", "Moab", "Tyre"))

		private val Esther = arrayOf(arrayOf("Ethiopia", "India",
				"Media", "Persia", "Tarshish"),
				arrayOf("Babylon", "Jerusalem"),
				arrayOf<String?>(null),
				arrayOf<String?>(null),
				arrayOf<String?>(null),
				arrayOf<String?>(null),
				arrayOf<String?>(null),
				arrayOf("Ethiopia", "India"),
				arrayOf<String?>(null),
				arrayOf("Media", "Persia"))

		private val Job = arrayOf(arrayOf("Chaldea", "Uz"),
				arrayOf("Tema"),
				arrayOf<String?>(null),
				arrayOf("Tema"),
				arrayOf<String?>(null),
				arrayOf("Sheba", "Tema"),
				arrayOf<String?>(null),
				arrayOf<String?>(null),
				arrayOf<String?>(null),
				arrayOf<String?>(null),
				arrayOf<String?>(null),
				arrayOf<String?>(null),
				arrayOf<String?>(null),
				arrayOf<String?>(null),
				arrayOf("Tema"),
				arrayOf<String?>(null),
				arrayOf<String?>(null),
				arrayOf<String?>(null),
				arrayOf<String?>(null),
				arrayOf<String?>(null),
				arrayOf<String?>(null),
				arrayOf("Ophir", "Tema"),
				arrayOf<String?>(null),
				arrayOf<String?>(null),
				arrayOf<String?>(null),
                arrayOf<String?>(null),
                arrayOf<String?>(null),
				arrayOf("Ethiopia", "Ophir"),
				arrayOf<String?>(null),
				arrayOf<String?>(null),
				arrayOf<String?>(null),
				arrayOf("Buz"),
				arrayOf<String?>(null),
                arrayOf<String?>(null),
				arrayOf<String?>(null),
				arrayOf<String?>(null),
                arrayOf<String?>(null),
				arrayOf<String?>(null),
				arrayOf<String?>(null),
				arrayOf("Jordan"),
				arrayOf<String?>(null),
				arrayOf("Tema"))

		private val Psalms = arrayOf(arrayOf<String?>(null),
				arrayOf<String?>(null),
                arrayOf<String?>(null),
				arrayOf<String?>(null),
				arrayOf("temple"),
				arrayOf<String?>(null),
				arrayOf<String?>(null),
				arrayOf<String?>(null),
				arrayOf<String?>(null),
				arrayOf<String?>(null),
				arrayOf("temple"),
				arrayOf<String?>(null),
				arrayOf<String?>(null),
				arrayOf("Israel"),
				arrayOf<String?>(null),
				arrayOf<String?>(null),
				arrayOf<String?>(null),
				arrayOf("temple"),
				arrayOf<String?>(null),
				arrayOf<String?>(null),
				arrayOf<String?>(null),
				arrayOf("Bashan", "Israel"),
				arrayOf<String?>(null),
				arrayOf<String?>(null),
				arrayOf("Israel"),
				arrayOf<String?>(null),
				arrayOf("temple"),
				arrayOf<String?>(null),
				arrayOf("Kadesh", "Lebanon", "temple"),
                arrayOf<String?>(null),
				arrayOf<String?>(null),
				arrayOf<String?>(null),
				arrayOf<String?>(null),
				arrayOf<String?>(null),
				arrayOf<String?>(null),
				arrayOf<String?>(null),
				arrayOf<String?>(null),
				arrayOf<String?>(null),
				arrayOf<String?>(null),
				arrayOf<String?>(null),
                arrayOf("Israel"),
				arrayOf("Jordan"),
				arrayOf<String?>(null),
				arrayOf<String?>(null),
				arrayOf("Ophir", "Tyre"),
				arrayOf<String?>(null),
				arrayOf<String?>(null),
				arrayOf("mount Zion", "temple", "Tarshish"),
				arrayOf<String?>(null),
				arrayOf("Israel"),
				arrayOf("Jerusalem", "Zion"),
				arrayOf<String?>(null),
				arrayOf("Israel"),
				arrayOf<String?>(null),
				arrayOf<String?>(null),
				arrayOf<String?>(null),
				arrayOf<String?>(null),
				arrayOf<String?>(null),
				arrayOf("Israel"),
				arrayOf("Ephraim", "Edom", "Gilead", "Moab",
						"Philistia", "Shechem", "Succoth"),
				arrayOf<String?>(null),
				arrayOf<String?>(null),
				arrayOf<String?>(null),
				arrayOf<String?>(null),
				arrayOf("Sion", "temple"),
				arrayOf<String?>(null),
				arrayOf<String?>(null),
				arrayOf("Bashan", "Egypt", "Ethiopia", "Israel",
						"Jerusalem", "Sinai", "temple"),
				arrayOf("Israel"),
				arrayOf<String?>(null),
				arrayOf("Israel"),
				arrayOf("Israel", "Lebanon", "Seba", "Sheba",
						"Tarshish"),
				arrayOf("Israel"),
				arrayOf("mount Zion"),
				arrayOf<String?>(null),
				arrayOf("Israel", "Salem"),
				arrayOf<String?>(null),
				arrayOf("Egypt", "Ephraim", "Ham", "Israel",
						"mount Zion", "Shiloh", "Zoan"),
				arrayOf("Jerusalem", "temple"),
				arrayOf("Egypt", "Ephraim", "Israel"),
				arrayOf("Egypt", "Israel", "Meribah"),
				arrayOf<String?>(null),
				arrayOf("Ammon", "Amalek", "Endor", "Edom", "Gebal",
						"Israel", "Moab", "Midian", "Tyre"),
				arrayOf<String?>(null),
				arrayOf<String?>(null),
				arrayOf<String?>(null),
				arrayOf("Babylon", "Ethiopia", "Philistia", "Rahab",
						"Tyre", "Zion"),
				arrayOf<String?>(null),
				arrayOf("Israel", "Rahab", "Tabor"),
				arrayOf<String?>(null),
				arrayOf<String?>(null),
				arrayOf("Lebanon"),
				arrayOf<String?>(null),
				arrayOf<String?>(null),
				arrayOf<String?>(null),
				arrayOf<String?>(null),
				arrayOf<String?>(null),
				arrayOf("Israel"),
				arrayOf<String?>(null),
				arrayOf<String?>(null),
				arrayOf<String?>(null),
				arrayOf("Jerusalem"),
				arrayOf("Israel"),
				arrayOf("Lebanon"),
				arrayOf("Canaan", "Egypt", "Ham", "Israel"),
				arrayOf("Baalpeor", "Canaan", "Egypt", "Horeb", "Ham",
						"Israel", "Red sea"),
				arrayOf<String?>(null),
				arrayOf("Ephraim", "Edom", "Gilead", "Moab",
						"Philistia", "Shechem", "Succoth"),
				arrayOf<String?>(null),
				arrayOf<String?>(null),
				arrayOf<String?>(null),
				arrayOf<String?>(null),
				arrayOf<String?>(null),
				arrayOf("Egypt", "Israel", "Jordan"),
				arrayOf("Israel"),
				arrayOf("Jerusalem"),
				arrayOf<String?>(null),
				arrayOf("Israel"),
				arrayOf<String?>(null),
				arrayOf("Kedar"),
				arrayOf("Israel"),
				arrayOf("Israel", "Jerusalem"),
				arrayOf<String?>(null),
				arrayOf("Israel"),
				arrayOf("Israel", "Jerusalem", "mount Zion"),
				arrayOf<String?>(null),
				arrayOf<String?>(null),
				arrayOf("Israel", "Jerusalem"),
				arrayOf("Israel"),
				arrayOf("Israel"),
				arrayOf("Israel"),
				arrayOf<String?>(null),
				arrayOf<String?>(null),
				arrayOf<String?>(null),
				arrayOf("Bashan", "Canaan", "Egypt", "Israel",
						"Jerusalem"),
				arrayOf("Bashan", "Egypt", "Israel", "Red sea"),
				arrayOf("Babylon", "Edom", "Jerusalem"),
				arrayOf("temple"),
				arrayOf<String?>(null),
				arrayOf<String?>(null),
				arrayOf<String?>(null),
				arrayOf<String?>(null),
				arrayOf<String?>(null),
				arrayOf<String?>(null),
				arrayOf<String?>(null),
				arrayOf<String?>(null),
				arrayOf("Israel", "Jerusalem"),
				arrayOf("Israel"),
				arrayOf("Israel"),
				arrayOf<String?>(null))

		private val Proverbs = arrayOf(arrayOf("Israel"),
			arrayOf<String?>(null),
            arrayOf<String?>(null), 
            arrayOf<String?>(null), 
            arrayOf<String?>(null), 
            arrayOf<String?>(null), 
            arrayOf("Egypt"), 
            arrayOf<String?>(null), 
            arrayOf<String?>(null), 
            arrayOf<String?>(null), 
            arrayOf<String?>(null), 
            arrayOf<String?>(null), 
            arrayOf<String?>(null), 
            arrayOf<String?>(null), 
            arrayOf<String?>(null), 
            arrayOf<String?>(null), 
            arrayOf<String?>(null), 
            arrayOf<String?>(null), 
            arrayOf<String?>(null), 
            arrayOf<String?>(null), 
            arrayOf<String?>(null), 
            arrayOf<String?>(null), 
            arrayOf<String?>(null), 
            arrayOf<String?>(null), 
            arrayOf<String?>(null), 
            arrayOf<String?>(null), 
            arrayOf<String?>(null), 
            arrayOf<String?>(null), 
            arrayOf<String?>(null), 
            arrayOf<String?>(null), 
            arrayOf<String?>(null))

		private val Ecclesiasties = arrayOf(arrayOf("Israel", "Jerusalem"), 
            arrayOf("Jerusalem"), 
            arrayOf<String?>(null), 
            arrayOf<String?>(null), 
            arrayOf<String?>(null), 
            arrayOf<String?>(null), 
            arrayOf<String?>(null), 
            arrayOf<String?>(null), 
            arrayOf<String?>(null), 
            arrayOf<String?>(null), 
            arrayOf<String?>(null), 
            arrayOf<String?>(null))

		private val Song_of_Solomon = arrayOf(arrayOf("Engedi", "Hazazontamar", 
            "Hazezontamar", "Jerusalem", "Kedar"), 
            arrayOf("Jerusalem"), 
            arrayOf("Israel", "Jerusalem", "Lebanon"), 
            arrayOf("Amana", "Gilead", "Lebanon"), 
            arrayOf("Jerusalem", "Lebanon"), 
            arrayOf("Gilead", "Jerusalem", "Tirzah"), 
            arrayOf("Bathrabbim", "Carmel", "Damascus", "Heshbon", "Lebanon"), 
            arrayOf("Jerusalem"))

		private val Isaiah = arrayOf(arrayOf("Gomorrah", "Israel", "Jerusalem", 
            "Sodom"), 
            arrayOf("Bashan", "Jerusalem", "Lebanon", "Tarshish"), 
            arrayOf("Jerusalem", "Sodom"), 
            arrayOf("Israel", "Jerusalem", "mount Zion"), 
            arrayOf("Israel", "Jerusalem"), 
            arrayOf<String?>(null), 
            arrayOf("Assyria", "Damascus", "Egypt", "Ephraim", "Israel", 
            "Jerusalem", "Syria", "Samaria"), 
            arrayOf("Assyria", "Damascus", "Israel", "Jerusalem", "mount Zion", 
            "Samaria", "Shiloah"), 
            arrayOf("Ephraim", "Galilee", "Israel", "Jordan", "Midian", "Syria", 
            "Samaria"), 
            arrayOf("Anathoth", "Assyria", "Arpad", "Carchemish", "Damascus", 
            "Egypt", "Gallim", "Gebim", "Gibeah", "Geba", "Hamath", "Israel", 
            "Jerusalem", "Lebanon", "Michmash", "Midian", "Madmenah", "Migron", 
            "mount Zion", "Nob", "Rama", "Ramah", "Samaria"), 
            arrayOf("Ammon", "Assyria", "Cush", "Egypt", "Ephraim", "Edom", 
            "Elam", "Hamath", "Israel", "Moab", "Pathros", "Shinar", "Zion"), 
            arrayOf("Israel"), 
            arrayOf("Arabia", "Babylon", "Gomorrah", "Ophir", "Sodom"), 
            arrayOf("Assyria", "Babylon", "Israel", "Lebanon", "Palestina"), 
            arrayOf("Beerelim", "Dibon", "Elealeh", "Eglaim", "Heshbon", 
            "Horonaim", "Jahaz", "Luhith", "Moab", "Medeba", "Nimrim", "Nebo", 
            "Zoar"), arrayOf("Arnon", "Elealeh", "Heshbon", "Jazer", "Moab", 
            "Sela", "wilderness"), 
            arrayOf("Aroer", "Damascus", "Ephraim", "Israel", "Syria", 
            "valley of Rephaim"), 
            arrayOf("Ethiopia", "mount Zion"), 
            arrayOf("Assyria", "Canaan", "Egypt", "Israel", "Zoan"), 
            arrayOf("Assyria", "Ashdod", "Egypt", "Ethiopia"), 
            arrayOf("Arabia", "Babylon", "Dedan", "Dumah", "Elam", "Israel", 
            "Kedar", "Media", "Seir", "Tema"), 
            arrayOf("Elam", "Jerusalem"), 
            arrayOf("Assyria", "Chaldea", "Egypt", "Tarshish", "Tyre"), 
            arrayOf("Israel", "Jerusalem", "mount Zion"), 
            arrayOf("Moab"), 
            arrayOf<String?>(null), 
            arrayOf("Assyria", "Egypt", "Israel", "Jerusalem"), 
            arrayOf("Ephraim", "Jerusalem", "mount Perazim", "valley of Gibeon"), 
            arrayOf("Israel", "Lebanon", "mount Zion"), 
            arrayOf("Assyria", "Egypt", "Hanes", "Israel", "Jerusalem", "Zoan"), 
            arrayOf("Assyria", "Egypt", "Israel", "Jerusalem", "mount Zion"), 
            arrayOf<String?>(null), 
            arrayOf("Bashan", "Carmel", "Jerusalem", "Lebanon"), 
            arrayOf("Bozrah"), 
            arrayOf("Carmel", "Lebanon"), 
            arrayOf("Assyria", "Egypt", "Hamath", "Jerusalem", "Lachish", 
            "Syria", "Samaria", "Sepharvaim", "Sephar"), 
            arrayOf("Assyria", "Carmel", "Ethiopia", "Gozan", "Hamath", "Haran", 
            "Hena", "Israel", "Jerusalem", "Libnah", "Lebanon", "Lachish", 
            "mount Zion", "Nineveh", "Rezeph", "Sepharvaim", "Sephar", 
            "Telassar"), 
            arrayOf("Assyria"), 
            arrayOf("Babylon"), 
            arrayOf("Israel", "Jerusalem", "Lebanon"), 
            arrayOf("Israel", "Jerusalem"), 
            arrayOf("Israel", "Kedar"), 
            arrayOf("Babylon", "Chaldea", "Egypt", "Ethiopia", "Israel", "Seba", 
            "wilderness"), 
            arrayOf("Israel", "Jerusalem", "temple"), 
            arrayOf("Egypt", "Ethiopia", "Israel"), 
            arrayOf("Israel", "Nebo"), 
            arrayOf("Babylon", "Chaldea", "Israel"), 
            arrayOf("Babylon", "Chaldea", "Israel"), 
            arrayOf("Israel"), 
            arrayOf<String?>(null), 
            arrayOf("Eden", "garden", "Jerusalem"), 
            arrayOf("Assyria", "Egypt", "Israel", "Jerusalem"), 
            arrayOf<String?>(null), 
            arrayOf("Israel"), 
            arrayOf("Israel"), 
            arrayOf("Israel"), 
            arrayOf<String?>(null), 
            arrayOf<String?>(null), 
            arrayOf<String?>(null), 
            arrayOf("Ephah", "Israel", "Kedar", "Lebanon", "Midian", "Nebaioth", 
            "Sheba", "Tarshish"), 
            arrayOf<String?>(null), 
            arrayOf("Jerusalem"), 
            arrayOf("Bozrah", "Edom", "Israel"), 
            arrayOf("Jerusalem"), 
            arrayOf("Jerusalem", "valley of Achor"), 
            arrayOf("Israel", "Jerusalem", "Javan", "Pul", "Tubal", "temple", 
            "Tarshish"))

		private val Jeremiah = arrayOf(arrayOf("Anathoth", "Jerusalem"), 
            arrayOf("Assyria", "Egypt", "Israel", "Jerusalem", "Kedar"), 
            arrayOf("Arabia", "Israel", "Jerusalem"), 
            arrayOf("Dan", "Ephraim", "Israel", "Jerusalem"), 
            arrayOf("Israel", "Jerusalem"), 
            arrayOf("Israel", "Jerusalem", "Sheba", "Tekoa"), 
            arrayOf("Egypt", "Ephraim", "Israel", "Jerusalem", "Shiloh", 
            "temple"), 
            arrayOf("Dan", "Gilead", "Jerusalem"), 
            arrayOf("Ammon", "Egypt", "Edom", "Israel", "Jerusalem", "Moab"), 
            arrayOf("Israel", "Tarshish", "Uphaz"), 
            arrayOf("Anathoth", "Egypt", "Israel", "Jerusalem"), 
            arrayOf("Israel", "Jordan"), 
            arrayOf("Ethiopia", "Euphrates", "Israel", "Jerusalem"), 
            arrayOf("Israel", "Jerusalem"), 
            arrayOf("Jerusalem"), 
            arrayOf("Egypt", "Israel"), 
            arrayOf("Israel", "Jerusalem"), 
            arrayOf("Israel", "Jerusalem", "Lebanon"), 
            arrayOf("Israel", "Jerusalem"), 
            arrayOf("Babylon", "Immer"), 
            arrayOf("Babylon", "Chaldea", "Israel"), 
            arrayOf("Bashan", "Babylon", "Chaldea", "Gilead", "Jerusalem", 
            "Lebanon"), 
            arrayOf("Egypt", "Gomorrah", "Israel", "Jerusalem", "Sodom", 
            "Samaria"), 
            arrayOf("Babylon", "Chaldea", "Egypt", "Israel", "Jerusalem", 
            "temple"), 
            arrayOf("Ammon", "Arabia", "Ashkelon", "Ashdod", "Buz", "Babylon", 
            "Chaldea", "Dedan", "Egypt", "Ekron", "Edom", "Elam", "Israel", 
            "Jerusalem", "Moab", "Tema", "Uz", "Zimri"), 
            arrayOf("Egypt", "Jerusalem", "Shiloh"), 
            arrayOf("Ammon", "Babylon", "Edom", "Israel", "Jerusalem", "Moab"), 
            arrayOf("Babylon", "Gibeon", "Israel"), 
            arrayOf("Anathoth", "Babylon", "Israel", "Jerusalem"), 
            arrayOf("Israel"), 
            arrayOf("Egypt", "Ephraim", "Gareb", "Israel", "Kidron", "Rama", 
            "Ramah", "Samaria"), 
            arrayOf("Anathoth", "Babylon", "Chaldea", "Egypt", "Israel", 
            "Jerusalem"), 
            arrayOf("Chaldea", "Israel", "Jerusalem"), 
            arrayOf("Azekah", "Babylon", "Egypt", "Israel", "Jerusalem", 
            "Lachish"), 
            arrayOf("Babylon", "Chaldea", "Israel", "Jerusalem", "Syria"), 
            arrayOf("Babylon", "Israel", "Jerusalem"), 
            arrayOf("Babylon", "Chaldea", "Egypt", "Israel", "Jerusalem"), 
            arrayOf("Babylon", "Chaldea", "Ethiopia", "Israel", "Jerusalem"), 
            arrayOf("Babylon", "Chaldea", "Ethiopia", "Hamath", "Israel", 
            "Jerusalem", "Jericho", "Riblah"), 
            arrayOf("Ammon", "Babylon", "Chaldea", "Edom", "Jerusalem", "Moab", 
            "Mizpah", "Rama", "Ramah"), 
            arrayOf("Ammon", "Bethlehem", "Babylon", "Chaldea", "Egypt", 
            "Gibeon", "Israel", "Mizpah", "Shechem", "Shiloh", "Samaria"), 
            arrayOf("Babylon", "Egypt", "Israel", "Jerusalem"), 
            arrayOf("Babylon", "Bethshemesh", "Chaldea", "Egypt", "Israel", 
            "Tahpanhes"), 
            arrayOf("Babylon", "Egypt", "Israel", "Jerusalem", "Migdol", 
            "Pathros", "Tahpanhes"), 
            arrayOf("Israel"), 
            arrayOf("Babylon", "Carmel", "Carchemish", "Egypt", "Ethiopia", 
            "Euphrates", "Gilead", "Israel", "Libya", "Migdol", "Tahpanhes", 
            "Tabor"), 
            arrayOf("Ashkelon", "Gaza"), 
            arrayOf("Aroer", "Arnon", "Bethgamul", "Bozrah", "Bethel", "Dibon", 
            "Elealeh", "Heshbon", "Horonaim", "Holon", "Israel", "Jahaz", 
            "Kiriathaim", "Luhith", "Mephaath", "Moab", "Nimrim", "Nebo", 
            "sea of Jazer", "Zoar"), 
            arrayOf("Ai", "Ammon", "Arpad", "Bozrah", "Babylon", "Damascus", 
            "Dedan", "Esau", "Edom", "Elam", "Gomorrah", "Hazor", "Hamath", 
            "Heshbon", "Israel", "Jordan", "Kedar", "Red sea", "Sodom", "Teman", 
            "Tema"), 
            arrayOf("Assyria", "Bashan", "Babylon", "Carmel", "Chaldea", 
            "Ephraim", "Gilead", "Gomorrah", "Israel", "Jordan", "Sodom", 
            "temple"), 
            arrayOf("Ararat", "Babylon", "Chaldea", "Euphrates", "Israel", 
            "Jerusalem", "Minni", "temple"), 
            arrayOf("Babylon", "Chaldea", "Hamath", "Jerusalem", "Jericho", 
            "Libnah", "Riblah"))

		private val Lamentations = arrayOf(arrayOf("Jerusalem"), 
            arrayOf("Israel", "Jerusalem"), 
            arrayOf<String?>(null), 
            arrayOf("Edom", "Jerusalem", "Sodom", "Uz", "Zion"), 
            arrayOf("Assyria", "Egypt"))

		private val Ezekiel = arrayOf(arrayOf("Chaldea", "Chebar"), 
            arrayOf("Israel"), 
            arrayOf("Chebar", "Israel", "Telabib"), 
            arrayOf("Israel", "Jerusalem"), 
            arrayOf("Israel", "Jerusalem"), 
            arrayOf("Israel"), 
            arrayOf("Israel"), 
            arrayOf("Israel", "Jerusalem", "temple"), 
            arrayOf("Israel", "Jerusalem"), 
            arrayOf("Chebar", "Israel"), 
            arrayOf("Chaldea", "Israel", "Jerusalem"), 
            arrayOf("Babylon", "Chaldea", "Israel", "Jerusalem"), 
            arrayOf("Israel", "Jerusalem"), 
            arrayOf("Dan", "Israel", "Jerusalem"), 
            arrayOf("Jerusalem"), 
            arrayOf("Assyria", "Canaan", "Chaldea", "Egypt", "Jerusalem", 
            "Sodom", "Syria", "Samaria"), 
            arrayOf("Babylon", "Egypt", "Israel", "Jerusalem", "Lebanon"), 
            arrayOf("Israel"), 
            arrayOf("Babylon", "Egypt", "Israel"), 
            arrayOf("Egypt", "Israel"), 
            arrayOf("Ammon", "Babylon", "Israel", "Jerusalem"), 
            arrayOf("Israel", "Jerusalem"), 
            arrayOf("Assyria", "Babylon", "Chaldea", "Egypt", "Jerusalem", "Koa", 
            "Shoa", "Samaria"), 
            arrayOf("Babylon", "Israel", "Jerusalem"), 
            arrayOf("Ammon", "Baalmeon", "Dedan", "Edom", "Israel", "Kiriathaim", 
            "Moab", "Seir", "Teman"), 
            arrayOf("Babylon", "Jerusalem"), 
            arrayOf("Arabia", "Arvad", "Asshur", "Bashan", "Chilmad", "Damascus", 
            "Dedan", "Dan", "Eden", "Egypt", "Geba", "Gebal", "Haran", "Helbon", 
            "Israel", "Javan", "Kedar", "Lebanon", "Minnith", "Minni", "Meshech", 
            "Persia", "Raamah", "Syria", "Sheba", "Tubal", "Tarshish", "Tyrus", 
            "Zidon"), 
            arrayOf("Eden", "Israel"), 
            arrayOf("Babylon", "Egypt", "Ethiopia", "Israel", "Pathros", 
            "Syene"), 
            arrayOf("Babylon", "Egypt", "Ethiopia", "Libya", "Pathros", 
            "Pibeseth", "Syene", "Zoan"), 
            arrayOf("Assyria", "Eden", "Egypt", "Lebanon"), 
            arrayOf("Asshur", "Babylon", "Egypt", "Edom", "Elam", "Meshech", 
            "Tubal"), 
            arrayOf("Israel", "Jerusalem"), 
            arrayOf("Israel"), 
            arrayOf("Israel", "mount Seir"), 
            arrayOf("Eden", "Israel", "Jerusalem"), 
            arrayOf("Ephraim", "Israel"), 
            arrayOf("Dedan", "Ethiopia", "Gog", "Israel", "Libya", "Magog", 
            "Meshech", "Persia", "Sheba", "Tubal", "Tarshish"), 
            arrayOf("Bashan", "Gog", "Hamonah", "Israel", "Magog", "Meshech", 
            "Tubal", "valley of Hamongog"), 
            arrayOf("Israel"), 
            arrayOf<String?>(null), 
            arrayOf<String?>(null), 
            arrayOf("Chebar", "Israel"), 
            arrayOf("Israel"), 
            arrayOf("Israel"), 
            arrayOf<String?>(null), 
            arrayOf("Berothah", "Damascus", "Engedi", "Hazazontamar", 
            "Hazezontamar", "Eneglaim", "Gilead", "great sea", "Hazarenan", 
            "Hethlon", "Hamath", "Hauran", "Israel", "Jordan", "Kadesh", 
            "Sibraim", "Tamar", "Zedad"), 
            arrayOf("Damascus", "Dan", "Ephraim", "great sea", "Hazarenan", 
            "Hethlon", "Hamath", "Israel", "Kadesh", "Tamar"))

		private val Daniel = arrayOf(arrayOf("Babylon", "Chaldea", "Israel", 
            "Jerusalem", "Mesha", "Shinar"), 
            arrayOf("Babylon", "Chaldea", "Mesha", "Syria"), 
            arrayOf("Babylon", "Chaldea", "Dura", "Mesha"), 
            arrayOf("Babylon", "Chaldea"), 
            arrayOf("Babylon", "Chaldea", "Jerusalem", "Media", "Persia"), 
            arrayOf("Jerusalem", "Persia"), 
            arrayOf("Babylon", "great sea"), 
            arrayOf("Dan", "Elam", "Media", "Persia", "Ulai"), 
            arrayOf("Chaldea", "Egypt", "Israel", "Jerusalem"), 
            arrayOf("Dan", "Hiddekel", "Persia", "Uphaz"), 
            arrayOf("Ammon", "Egypt", "Ethiopia", "Edom", "Libya", "Moab", 
            "Persia"), 
            arrayOf<String?>(null))

		private val Hosea = arrayOf(arrayOf("Israel", "Jezreel", 
            "valley of Jezreel"), 
            arrayOf("Egypt", "Jezreel", "valley of Achor"), 
            arrayOf("Israel"), 
            arrayOf("Bethaven", "Ephraim", "Gilgal", "Israel"), 
            arrayOf("Assyria", "Bethaven", "Ephraim", "Gibeah", "Israel", 
            "Mizpah", "Rama", "Ramah", "Tabor"), 
            arrayOf("Ephraim", "Gilead", "Israel"), 
            arrayOf("Assyria", "Egypt", "Ephraim", "Israel", "Samaria"), 
            arrayOf("Assyria", "Egypt", "Ephraim", "Israel", "Samaria", 
            "temple"), 
            arrayOf("Assyria", "Baalpeor", "Egypt", "Ephraim", "Gilgal", 
            "Gibeah", "Israel", "Memphis"), 
            arrayOf("Assyria", "Betharbel", "Bethel", "Bethaven", "Ephraim", 
            "Gibeah", "Israel", "Samaria"), 
            arrayOf("Assyria", "Admah", "Egypt", "Ephraim", "Israel", "Zeboim"), 
            arrayOf("Assyria", "Bethel", "Egypt", "Ephraim", "Gilead", "Gilgal", 
            "Israel", "Syria"), 
            arrayOf("Egypt", "Ephraim", "Israel", "Samaria"), 
            arrayOf("Asshur", "Ephraim", "Israel", "Lebanon"))

		private val Joel = arrayOf(arrayOf<String?>(null), 
            arrayOf("Eden", "Israel", "Jerusalem", "mount Zion"), 
            arrayOf("Egypt", "Edom", "Israel", "Jerusalem", "temple", "Tyre", 
            "valley of Shittim", "Zidon", "Zion"))

		private val Amos = arrayOf(arrayOf("Ammon", "Ashkelon", "Ashdod", 
            "Bozrah", "Carmel", "Damascus", "Ekron", "Edom", "Gilead", "Gaza", 
            "Israel", "Jerusalem", "Syria", "Teman", "Tekoa"), 
            arrayOf("Egypt", "Edom", "Israel", "Jerusalem", "Moab"), 
            arrayOf("Ashdod", "Bethel", "Damascus", "Egypt", "Israel", 
            "Samaria"), 
            arrayOf("Bashan", "Bethel", "Egypt", "Gilgal", "Gomorrah", "Israel", 
            "Sodom", "Samaria"), 
            arrayOf("Beersheba", "Beer", "Bethel", "Damascus", "Gilgal", 
            "Israel"), 
            arrayOf("Calneh", "Gath", "Hamath", "Israel", "Samaria"), 
            arrayOf("Bethel", "Israel"), 
            arrayOf("Beersheba", "Dan", "Egypt", "Israel", "Samaria", "temple"), 
            arrayOf("Carmel", "Egypt", "Ethiopia", "Edom", "Israel", "Syria"))

		private val Obadiah = arrayOf(arrayOf("Canaan", "Ephraim", "Esau", 
            "Edom", "Gilead", "Israel", "Jerusalem", "mount Zion", "Samaria", 
            "Teman", "Tema", "Zarephath"))

		private val Jonah = arrayOf(arrayOf("Joppa", "Nineveh", "Tarshish"), 
            arrayOf("temple"), 
            arrayOf("Nineveh"), 
            arrayOf("Nineveh", "Tarshish"))

		private val Micah = arrayOf(arrayOf("Achzib", "Adullam", "Bethezel", 
            "Gath", "Israel", "Jerusalem", "Lachish", "Mareshah", 
            "Moreshethgath", "Maroth", "Moresheth", "Samaria", "temple", 
            "Zaanan"), 
            arrayOf("Bozrah", "Israel"), 
            arrayOf("Israel", "Jerusalem"), 
            arrayOf("Babylon", "Jerusalem", "mount Zion"), 
            arrayOf("Assyria", "Bethlehem", "Israel", "Nimrod"), 
            arrayOf("Egypt", "Gilgal", "Israel", "Moab", "Shittim"), 
            arrayOf("Assyria", "Bashan", "Carmel", "Egypt", "Gilead"))

		private val Nahum = arrayOf(arrayOf("Bashan", "Carmel", "Lebanon", 
            "Nineveh"), 
            arrayOf("Israel", "Nineveh"), 
            arrayOf("Assyria", "Egypt", "Ethiopia", "Nineveh"))

		private val Habakkuk = arrayOf(arrayOf("Chaldea"), 
            arrayOf("Lebanon", "temple"), 
            arrayOf("Cushan", "Midian", "mount Paran", "Teman"))

		private val Zephaniah = arrayOf(arrayOf("Jerusalem"), 
            arrayOf("Ammon", "Ashkelon", "Assyria", "Ashdod", "Canaan", 
            "Ethiopia", "Ekron", "Gaza", "Gomorrah", "Israel", "Moab", 
            "Nineveh", "Sodom"), 
            arrayOf("Ethiopia", "Israel", "Jerusalem"))

		private val Haggai = arrayOf(arrayOf<String?>(null), 
            arrayOf("Egypt", "temple"))

		private val Zechariah = arrayOf(arrayOf("Israel", "Jerusalem"), 
            arrayOf("Babylon", "Jerusalem"), 
            arrayOf("Jerusalem"), 
            arrayOf<String?>(null), 
            arrayOf("Shinar"), 
            arrayOf("Babylon", "temple"), 
            arrayOf("Jerusalem"), 
            arrayOf("Israel", "Jerusalem", "temple"), 
            arrayOf("Ashkelon", "Ashdod", "Damascus", "Ephraim", "Ekron", 
            "Greece", "Gaza", "Hamath", "Hadrach", "Israel", "Jerusalem"), 
            arrayOf("Assyria", "Egypt", "Ephraim", "Gilead", "Lebanon"), 
            arrayOf("Bashan", "Israel", "Jordan", "Lebanon"), 
            arrayOf("Hadadrimmon", "Israel", "Jerusalem", "Megiddo"), 
            arrayOf("Jerusalem"), 
            arrayOf("Azal", "Canaan", "Egypt", "Geba", "Jerusalem", 
            "mount of Olives", "Rimmon"))

		private val Malachi = arrayOf(arrayOf("Esau", "Edom", "Israel"), 
            arrayOf("Israel", "Jerusalem"), 
            arrayOf("Jerusalem", "temple"), 
            arrayOf("Horeb", "Israel"))

		/**
		 * New Testament books of the Bible.
		 */

		private val Matthew = arrayOf(arrayOf("Babylon"), 
            arrayOf("Bethlehem", "Judaea", "Jerusalem", "Israel", "Egypt", 
            "Rama", "Ramah", "Galilee", "Nazareth"), 
            arrayOf("the wilderness", "Judaea", "Jerusalem", "Jordan", 
            "Galilee"), 
            arrayOf("the wilderness", "temple", "Galilee", "Nazareth", 
            "Capernaum", "beyond the Jordan", "sea of Galilee", "Syria", 
            "Decapolis", "Jerusalem", "Judaea"), 
            arrayOf("Jerusalem"), 
            arrayOf<String?>(null), 
            arrayOf<String?>(null), 
            arrayOf("Capernaum", "Israel", "country of the Gadarenes"), 
            arrayOf("Israel"), 
            arrayOf("Israel", "Sodom", "Gomorrha"), 
            arrayOf("the wilderness", "Chorazin", "Bethsaida", "Tyre", "Sidon", 
            "Capernaum", "Sodom"), 
            arrayOf("temple", "Nineveh", "the south"), 
            arrayOf("his own country"), 
            arrayOf("Gennesaret"), 
            arrayOf("Jerusalem", "Tyre", "Sidon", "Israel", "sea of Galilee", 
            "Magdala"), 
            arrayOf("Caesarea Philippi", "Jerusalem"), 
            arrayOf("an high mountain", "Galilee", "Capernaum"), 
            arrayOf<String?>(null), 
            arrayOf("Galilee", "Judaea", "beyond the Jordan", "Israel"), 
            arrayOf("Jerusalem", "Jericho"), 
            arrayOf("Jerusalem", "Bethphage", "mount of Olives", "Sion", 
            "Nazareth", "Galilee", "temple", "Bethany"), 
            arrayOf<String?>(null), 
            arrayOf("temple", "Jerusalem"), 
            arrayOf("temple", "mount of Olives", "Judaea", "the wilderness"), 
            arrayOf<String?>(null), arrayOf("palace", "Bethany",
			"at thy house", "mount of Olives", "Galilee", "Gethsemane", "temple",
			"Nazareth"),
            arrayOf("temple", "Israel", "stood before the governor", 
            "common hall", "Cyrene", "Golgotha", "place of a skull", "Galilee", 
            "Arimathaea", "his own new tomb", "unto Pilate"), 
            arrayOf("Galilee"))

		private val Mark = arrayOf(arrayOf("the wilderness", "Judaea", 
            "Jerusalem", "Jordan", "Nazareth", "Galilee", "sea of Galilee", 
            "Capernaum"), 
            arrayOf("Capernaum"), 
            arrayOf("Galilee", "Judaea", "Jerusalem", "Idumaea", 
            "beyond the Jordan", "Tyre", "Sidon"), 
            arrayOf<String?>(null), 
            arrayOf("country of the Gadarenes", "Decapolis"), 
            arrayOf("Gomorrha", "his own country", "Galilee", "Bethsaida", 
            "Gennesaret"), 
            arrayOf("Jerusalem", "Tyre", "Sidon", "sea of Galilee", "Decapolis"), 
            arrayOf("Dalmanutha", "Bethsaida", "Caesarea Philippi"), 
            arrayOf("an high mountain", "Galilee", "Capernaum"), 
            arrayOf("Judaea", "beyond the Jordan", "Jerusalem", "Jericho", 
            "Nazareth"), 
            arrayOf("Jerusalem", "Bethphage", "Bethany", "mount of Olives", 
            "temple"), 
            arrayOf("Israel", "temple"), 
            arrayOf("temple", "mount of Olives", "Judaea"), 
            arrayOf("Bethany", "upper room", "mount of Olives", "Galilee", 
            "Gethsemane", "temple", "palace"), 
            arrayOf("Praetorium", "Cyrene", "Golgotha", "place of a skull", 
            "temple", "Israel", "Galilee", "Jerusalem", "Arimathaea", 
            "sepulchre"), 
            arrayOf("Nazareth", "Galilee"))

		private val Luke = arrayOf(arrayOf("Judaea", "temple", "Israel", 
            "Galilee", "Nazareth", "the wilderness"), 
            arrayOf("Syria", "Galilee", "Nazareth", "Judaea", "Bethlehem", 
            "Jerusalem", "Israel", "temple"), 
            arrayOf("Judaea", "Galilee", "Ituraea", "Trachonitis", "Abilene", 
            "the wilderness", "Jordan"), 
            arrayOf("Jordan", "the wilderness", "Jerusalem", "temple", 
            "Galilee", "Nazareth", "Capernaum", "his own country", "Israel", 
            "Sidon", "Judaea"), 
            arrayOf("lake of Gennesaret", "Galilee", "Judaea", "Jerusalem"), 
            arrayOf("Judaea", "Jerusalem", "Tyre", "Sidon"), 
            arrayOf("Capernaum", "Israel", "Nain", "Judaea", "the wilderness"), 
            arrayOf("country of the Gadarenes", "Galilee"), 
            arrayOf("Bethsaida", "Jerusalem"), 
            arrayOf("Sodom", "Chorazin", "Bethsaida", "Tyre", "Sidon", 
            "Capernaum", "Jerusalem", "Jericho"), 
            arrayOf("Nineveh", "the south"), 
            arrayOf<String?>(null), 
            arrayOf("Siloam", "Jerusalem"), 
            arrayOf<String?>(null), 
            arrayOf<String?>(null), 
            arrayOf<String?>(null), 
            arrayOf("Jerusalem", "Samaria", "Galilee", "Sodom"), 
            arrayOf("temple", "Jerusalem", "Jericho", "Nazareth"), 
            arrayOf("Jericho", "Jerusalem", "Bethphage", "Bethany", 
            "mount of Olives", "temple"), 
            arrayOf("temple"), 
            arrayOf("temple", "Jerusalem", "Judaea", "mount called Olivet"), 
            arrayOf("upper room", "Israel", "mount of Olives", "temple", 
            "the hall"), 
            arrayOf("unto Pilate", "Judaea", "Galilee", "Jerusalem", "Cyrene", 
            "The Skull", "temple", "Arimathaea", "sepulchre"), 
            arrayOf("Galilee", "Emmaus", "Jerusalem", "Nazareth", "Israel", 
            "Bethany", "temple"))

		private val John = arrayOf(arrayOf("Jerusalem", "the wilderness", 
            "Bethabara beyond Jordan", "Israel", "Galilee", "Bethsaida", "Nazareth"), 
            arrayOf("Cana", "Galilee", "Capernaum", "Jerusalem", "temple"), 
            arrayOf("Israel", "the wilderness", "Judaea", "Aenon", "Salim", 
            "Jordan"), 
            arrayOf("Judaea", "Galilee", "Samaria", "Sychar", "Jerusalem", 
            "his own country", "Cana", "Capernaum"), 
            arrayOf("Jerusalem", "Bethesda", "temple"), 
            arrayOf("sea of Galilee", "sea of Tiberias", "Capernaum", "Tiberias", 
            "the wilderness"), 
            arrayOf("Galilee", "Judaea", "temple", "Jerusalem", "Bethlehem"), 
            arrayOf("mount of Olives", "temple"), 
            arrayOf("Siloam"), 
            arrayOf("Jerusalem", "temple", "across the Jordan"), 
            arrayOf("Bethany", "Judaea", "Jerusalem", "the wilderness", "Ephraim", 
            "temple"), 
            arrayOf("Bethany", "Jerusalem", "Israel", "Sion", "Bethsaida", 
            "Galilee"), 
            arrayOf<String?>(null), 
            arrayOf<String?>(null), 
            arrayOf<String?>(null), 
            arrayOf<String?>(null), 
            arrayOf<String?>(null), 
            arrayOf("brook Cedron", "garden", "Nazareth", "palace", 
            "hall of judgment", "judgment hall"), 
            arrayOf("the Pavement", "Gabbatha", "place of a skull", "Golgotha", 
            "Arimathaea", "Jesus' Tomb"), 
            arrayOf<String?>(null), 
            arrayOf("sea of Tiberias", "Cana", "Galilee"))

		private val Acts = arrayOf(arrayOf("Jerusalem", "Israel", "Judaea", 
            "Samaria", "Galilee", "mount called Olivet", "upper room", 
            "The field of blood"), 
            arrayOf("Jerusalem", "Mesopotamia", "Judaea", "Cappadocia", "Pontus", 
            "Asia", "Phrygia", "Pamphylia", "Egypt", "Libya", "Cyrene", "Rome", 
            "Israel", "Nazareth", "temple"), 
            arrayOf("temple", "Nazareth", "Israel"), 
            arrayOf("temple", "Jerusalem", "Israel", "Nazareth", "Cyprus"), 
            arrayOf("Jerusalem", "temple", "Israel"), 
            arrayOf("Syrian Antioch", "Jerusalem", "Cilicia", "Asia", 
            "Nazareth"), 
            arrayOf("Mesopotamia", "Charran", "land of the Chaldaeans", "Egypt", 
            "Israel", "wilderness", "mount Sinai", "Babylon"), 
            arrayOf("Jerusalem", "Judaea", "Samaria", "Gaza", "Azotus", 
            "Caesarea"), 
            arrayOf("Damascus", "Jerusalem", "Tarsus", "Israel", "Caesarea", 
            "Judaea", "Galilee", "Samaria", "Lydda", "Saron", "Joppa"), 
            arrayOf("Caesarea", "Joppa", "Israel", "Judaea", "Galilee", 
            "Nazareth", "Jerusalem"), 
            arrayOf("Judaea", "Jerusalem", "Caesarea", "Phenice", "Cyprus", 
            "Syrian Antioch", "Cyrene", "Tarsus"), 
            arrayOf("Judaea", "Caesarea", "Tyre", "Sidon", "Jerusalem"), 
            arrayOf("Syrian Antioch", "Cyrene", "Seleucia", "Cyprus", "Salamis", 
            "Paphos", "Perga", "Pamphylia", "Jerusalem", "Pisidian Antioch", 
            "Israel", "Egypt", "wilderness", "Canaan", "Galatia", "Iconium"), 
            arrayOf("Iconium", "Lystra", "Derbe", "Lycaonia", "Pisidian Antioch", 
            "Pisidia", "Pamphylia", "Perga", "Attalia", "Syrian Antioch"), 
            arrayOf("Judaea", "Jerusalem", "Phenice", "Samaria", 
            "Syrian Antioch", "Syria", "Cilicia", "Pamphylia", "Cyprus"), 
            arrayOf("Derbe", "Lystra", "Iconium", "Jerusalem", "Phrygia", 
            "Galatia", "Asia", "Mysia", "Bithynia", "Troas", "Macedonia", 
            "Samothracia", "Neapolis", "Philippi"), 
            arrayOf("Amphipolis", "Apollonia", "Thessalonica", "Berea", 
            "Athens"), 
            arrayOf("Athens", "Corinth", "Pontus", "Italy", "Rome", "Macedonia", 
            "Achaia", "Syria", "Cenchrea", "Ephesus", "Caesarea", 
            "Syrian Antioch", "Galatia", "Phrygia", "Alexandria"), 
            arrayOf("Corinth", "Ephesus", "Macedonia", "Achaia", "Jerusalem", 
            "Rome", "Asia"), 
            arrayOf("Macedonia", "Greece", "Syria", "Berea", "Derbe", "Troas", 
            "Philippi", "Assos", "Mitylene", "Chios", "Samos", "Miletus", 
            "Ephesus", "Asia", "Jerusalem"), 
            arrayOf("Cos", "Rhodes", "Patara", "Phenice", "Cyprus", "Syria", 
            "Tyre", "Jerusalem", "Ptolemais", "Caesarea", "Judaea", "temple", 
            "Asia", "Israel", "Egypt", "Tarsus", "Cilicia"), 
            arrayOf("Tarsus", "Cilicia", "Damascus", "Jerusalem", "Nazareth", 
            "temple"), 
            arrayOf("Jerusalem", "Rome", "Caesarea", "Antipatris", "Cilicia"), 
            arrayOf("temple", "Jerusalem", "Asia"), 
            arrayOf("Jerusalem", "Caesarea", "temple"), 
            arrayOf("Jerusalem", "Nazareth", "Damascus", "Judaea", "temple"), 
            arrayOf("Adramyttium", "Asia", "Macedonia", "Thessalonica", "Sidon", 
            "Cyprus", "Cilicia", "Pamphylia", "Myra", "Lycia", "Alexandria", 
            "Italy", "Cnidus", "Crete", "Salmone", "The fair havens", "Lasea", 
            "Phoenix", "Clauda"), 
            arrayOf("Melita", "Alexandria", "Syracuse", "Rhegium", "Puteoli", 
            "Rome", "Appii", "The three taverns", "Jerusalem", "Israel", 
            "Judaea"))

		private val Romans = arrayOf(arrayOf("Rome"),
			arrayOf<String?>(null),
			arrayOf<String?>(null),
			arrayOf<String?>(null),
			arrayOf<String?>(null),
            arrayOf<String?>(null),
			arrayOf<String?>(null),
			arrayOf<String?>(null),
			arrayOf("Gomorrha", "Israel", "Sion", "Sodom"),
			arrayOf("Israel"),
			arrayOf("Israel", "Sion"),
			arrayOf<String?>(null),
			arrayOf<String?>(null),
			arrayOf<String?>(null),
			arrayOf("Achaia", "Illyricum", "Jerusalem", "Judaea", "Macedonia",
            "Spain"),
			arrayOf("Achaia", "Cenchrea"))

		private val First_Corinthians = arrayOf(arrayOf("Corinth"),
            arrayOf<String?>(null),
			arrayOf("temple"),
			arrayOf<String?>(null),
			arrayOf<String?>(null),
			arrayOf("temple"),
			arrayOf<String?>(null),
			arrayOf("temple"),
			arrayOf("temple"),
			arrayOf("Israel", "wilderness"),
			arrayOf<String?>(null),
			arrayOf<String?>(null),
			arrayOf<String?>(null),
			arrayOf<String?>(null),
			arrayOf("Ephesus"),
			arrayOf("Achaia", "Asia", "Ephesus", "Galatia", "Jerusalem",
			"Macedonia"))

		private val Second_Corinthians = arrayOf(arrayOf("Achaia", "Asia",
            "Corinth", "Judaea", "Macedonia"),
            arrayOf("Macedonia", "Troas"),
			arrayOf("Israel"),
			arrayOf<String?>(null),
			arrayOf<String?>(null),
			arrayOf("Corinth", "temple"),
			arrayOf("Macedonia"),
			arrayOf("Macedonia"),
			arrayOf("Achaia", "Macedonia"),
			arrayOf<String?>(null),
			arrayOf("Achaia", "Damascus", "Israel", "Macedonia"),
			arrayOf<String?>(null),
			arrayOf<String?>(null))

		private val Galatians = arrayOf(arrayOf("Arabia", "Cilicia", "Damascus",
            "Galatia", "Jerusalem", "Judaea", "Syria"),
			arrayOf("Jerusalem"),
			arrayOf("Galatia"),
			arrayOf("Arabia", "Jerusalem", "mount Sinai"),
			arrayOf<String?>(null),
			arrayOf("Israel"))

		private val Ephesians = arrayOf(arrayOf("Ephesus"),
            arrayOf("Israel", "temple"),
			arrayOf<String?>(null),
			arrayOf<String?>(null),
			arrayOf<String?>(null),
			arrayOf<String?>(null))

		private val Philippians = arrayOf(arrayOf("Philippi"),
            arrayOf<String?>(null),
			arrayOf("Israel"),
			arrayOf("Macedonia", "Philippi", "Thessalonica"))

		private val Colossians = arrayOf(arrayOf<String?>(null),
			arrayOf("Laodicea"),
            arrayOf<String?>(null),
			arrayOf("Hierapolis", "Laodicea"))

		private val First_Thessalonians = arrayOf(arrayOf("Achaia", "Macedonia"),
			arrayOf("Judaea", "Philippi"),
            arrayOf("Athens"),
			arrayOf("Macedonia"),
            arrayOf<String?>(null))

		private val Second_Thessalonians = arrayOf(arrayOf<String?>(null),
			arrayOf("temple"),
            arrayOf<String?>(null))

		private val First_Timothy = arrayOf(arrayOf("Ephesus", "Macedonia"),
				arrayOf<String?>(null),
				arrayOf<String?>(null),
				arrayOf<String?>(null),
				arrayOf<String?>(null),
				arrayOf<String?>(null))

		private val Second_Timothy = arrayOf(arrayOf("Asia", "Ephesus", "Rome"),
			arrayOf<String?>(null),
			arrayOf("Iconium", "Lystra"),
            arrayOf("Corinth", "Dalmatia", "Ephesus", "Galatia", "Thessalonica",
            "Troas"))

		private val Titus = arrayOf(arrayOf("Crete"),
            arrayOf<String?>(null),
			arrayOf("Nicopolis"))

		private val Philemon = arrayOf(arrayOf<String?>(null))

		private val Hebrews = arrayOf(arrayOf<String?>(null),
			arrayOf<String?>(null),
			arrayOf("Egypt", "the wilderness", "wilderness"),
            arrayOf<String?>(null),
			arrayOf<String?>(null),
			arrayOf<String?>(null),
			arrayOf("Salem"),
			arrayOf("Egypt", "Israel"),
			arrayOf<String?>(null),
			arrayOf<String?>(null),
			arrayOf("Egypt", "Israel", "Jericho", "Red sea"),
            arrayOf("Esau", "Jerusalem", "Sion"),
            arrayOf("Italy"))

		private val James = arrayOf(arrayOf<String?>(null),
			arrayOf<String?>(null),
			arrayOf<String?>(null),
			arrayOf<String?>(null),
			arrayOf<String?>(null))

		private val First_Peter = arrayOf(arrayOf("Asia", "Bithynia",
			"Cappadocia", "Galatia", "Pontus"),
            arrayOf("Sion"),
            arrayOf<String?>(null),
			arrayOf<String?>(null),
			arrayOf("Babylon"))

		private val Second_Peter = arrayOf(arrayOf<String?>(null),
			arrayOf("Gomorrha", "Sodom"),
            arrayOf<String?>(null))

		private val First_John = arrayOf(arrayOf<String?>(null),
			arrayOf<String?>(null),
			arrayOf<String?>(null),
			arrayOf<String?>(null),
			arrayOf<String?>(null))

		private val Second_John = arrayOf(arrayOf<String?>(null))

		private val Third_John = arrayOf(arrayOf<String?>(null))

		private val Jude = arrayOf(arrayOf("Egypt", "Gomorrha", "Sodom"))

		private val Revelations = arrayOf(arrayOf("Asia", "Ephesus", "Laodicea",
			"Philadelphia", "Pergamos", "Patmos", "Sardis", "Smyrna", "Thyatira"),
            arrayOf("Ephesus", "Israel", "Pergamos", "Smyrna", "Thyatira"),
            arrayOf("Jerusalem", "Laodicea", "Philadelphia", "Sardis", "temple"),
            arrayOf<String?>(null),
			arrayOf<String?>(null),
			arrayOf<String?>(null),
			arrayOf("Israel", "temple"),
            arrayOf<String?>(null),
			arrayOf("Euphrates"),
            arrayOf<String?>(null),
			arrayOf("Egypt", "Sodom", "temple"),
            arrayOf<String?>(null),
			arrayOf<String?>(null),
			arrayOf("Babylon", "Sion", "temple"),
            arrayOf("temple"),
            arrayOf("Babylon", "Euphrates", "temple"),
			arrayOf<String?>(null),
			arrayOf("Babylon"),
            arrayOf<String?>(null),
			arrayOf("Gog", "Magog"),
            arrayOf("Israel", "Jerusalem", "temple"),
            arrayOf<String?>(null))
	}

}
